// Complete Global Countries Data for Port Directory
// All 195 Countries with comprehensive port, trade and geographic data
// Data sources: UN/LOCODE, World Bank, WTO, CIA World Factbook

export interface Port {
  unLoCode: string;
  name: string;
  type: 'sea' | 'air' | 'dry' | 'river';
  coordinates: { lat: number; lng: number };
  throughput?: string;
}

export interface CountryPortData {
  code: string;
  name: string;
  flag: string;
  region: string;
  capital: string;
  currency: string;
  language: string;
  timezone: string;
  coastline: string;
  population: string;
  gdp: string;
  exports: string[];
  imports: string[];
  neighbours: string[];
  tradeAgreements: string[];
  seaPorts: Port[];
  airports: Port[];
  dryPorts: Port[];
}

// Complete country data for all 195 countries
export const ALL_COUNTRIES: CountryPortData[] = [
  // A
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', region: 'Asia', capital: 'Kabul', currency: 'Afghani', language: 'Pashto, Dari', timezone: 'UTC+4:30', coastline: 'Landlocked', population: '38.9M', gdp: '$19B', exports: ['Fruits', 'Nuts', 'Carpets', 'Gemstones'], imports: ['Food', 'Petroleum', 'Machinery'], neighbours: ['Pakistan', 'Iran', 'Turkmenistan', 'Uzbekistan', 'Tajikistan', 'China'], tradeAgreements: ['SAFTA', 'WTO', 'ECO'], seaPorts: [], airports: [{ unLoCode: 'AFKBL', name: 'Kabul Airport', type: 'air', coordinates: { lat: 34.5658, lng: 69.2123 }, throughput: '50K tons' }], dryPorts: [{ unLoCode: 'AFKBL', name: 'Kabul Dry Port', type: 'dry', coordinates: { lat: 34.5553, lng: 69.2075 } }] },
  { code: 'AL', name: 'Albania', flag: '🇦🇱', region: 'Europe', capital: 'Tirana', currency: 'Lek', language: 'Albanian', timezone: 'UTC+1', coastline: '362 km', population: '2.9M', gdp: '$15B', exports: ['Textiles', 'Footwear', 'Minerals'], imports: ['Machinery', 'Food', 'Chemicals'], neighbours: ['Montenegro', 'Kosovo', 'North Macedonia', 'Greece'], tradeAgreements: ['CEFTA', 'EU Stabilization', 'WTO'], seaPorts: [{ unLoCode: 'ALDUR', name: 'Durrës', type: 'sea', coordinates: { lat: 41.3116, lng: 19.4503 }, throughput: '300K TEU' }, { unLoCode: 'ALVLR', name: 'Vlorë', type: 'sea', coordinates: { lat: 40.4667, lng: 19.4833 } }], airports: [{ unLoCode: 'ALTIA', name: 'Tirana Airport', type: 'air', coordinates: { lat: 41.4147, lng: 19.7206 }, throughput: '35K tons' }], dryPorts: [] },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', region: 'Africa', capital: 'Algiers', currency: 'Dinar', language: 'Arabic, Berber', timezone: 'UTC+1', coastline: '998 km', population: '44M', gdp: '$184B', exports: ['Petroleum', 'Natural Gas', 'Chemicals'], imports: ['Machinery', 'Food', 'Vehicles'], neighbours: ['Tunisia', 'Libya', 'Niger', 'Mali', 'Mauritania', 'Morocco'], tradeAgreements: ['GAFTA', 'EU Association', 'AU'], seaPorts: [{ unLoCode: 'DZALG', name: 'Algiers', type: 'sea', coordinates: { lat: 36.8, lng: 3.05 }, throughput: '1.2M TEU' }, { unLoCode: 'DZORN', name: 'Oran', type: 'sea', coordinates: { lat: 35.7, lng: -0.63 }, throughput: '600K TEU' }, { unLoCode: 'DZBJA', name: 'Bejaia', type: 'sea', coordinates: { lat: 36.75, lng: 5.08 }, throughput: '450K TEU' }], airports: [{ unLoCode: 'DAAG', name: 'Algiers Airport', type: 'air', coordinates: { lat: 36.69, lng: 3.22 }, throughput: '100K tons' }], dryPorts: [] },
  { code: 'AD', name: 'Andorra', flag: '🇦🇩', region: 'Europe', capital: 'Andorra la Vella', currency: 'Euro', language: 'Catalan', timezone: 'UTC+1', coastline: 'Landlocked', population: '77K', gdp: '$3.3B', exports: ['Tobacco', 'Furniture'], imports: ['Consumer Goods', 'Food'], neighbours: ['France', 'Spain'], tradeAgreements: ['EU Customs Union'], seaPorts: [], airports: [], dryPorts: [{ unLoCode: 'ADALV', name: 'Andorra Dry Port', type: 'dry', coordinates: { lat: 42.51, lng: 1.52 } }] },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', region: 'Africa', capital: 'Luanda', currency: 'Kwanza', language: 'Portuguese', timezone: 'UTC+1', coastline: '1,600 km', population: '33M', gdp: '$86B', exports: ['Crude Oil', 'Diamonds', 'Coffee'], imports: ['Machinery', 'Food', 'Vehicles'], neighbours: ['Congo', 'DR Congo', 'Zambia', 'Namibia'], tradeAgreements: ['SADC', 'AfCFTA', 'EPA'], seaPorts: [{ unLoCode: 'AOLAD', name: 'Luanda', type: 'sea', coordinates: { lat: -8.78, lng: 13.23 }, throughput: '750K TEU' }, { unLoCode: 'AOLBX', name: 'Lobito', type: 'sea', coordinates: { lat: -12.35, lng: 13.53 }, throughput: '250K TEU' }], airports: [{ unLoCode: 'FNLU', name: 'Luanda Airport', type: 'air', coordinates: { lat: -8.86, lng: 13.23 }, throughput: '60K tons' }], dryPorts: [] },
  { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬', region: 'Caribbean', capital: "St. John's", currency: 'East Caribbean Dollar', language: 'English', timezone: 'UTC-4', coastline: '153 km', population: '98K', gdp: '$1.8B', exports: ['Petroleum Products', 'Bedding'], imports: ['Food', 'Machinery'], neighbours: [], tradeAgreements: ['CARICOM', 'EPA', 'CSME'], seaPorts: [{ unLoCode: 'AGANU', name: "St. John's", type: 'sea', coordinates: { lat: 17.12, lng: -61.85 }, throughput: '50K TEU' }], airports: [{ unLoCode: 'TAPA', name: 'V.C. Bird Airport', type: 'air', coordinates: { lat: 17.14, lng: -61.79 } }], dryPorts: [] },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', region: 'South America', capital: 'Buenos Aires', currency: 'Peso', language: 'Spanish', timezone: 'UTC-3', coastline: '4,989 km', population: '45M', gdp: '$383B', exports: ['Soybeans', 'Corn', 'Beef', 'Wheat'], imports: ['Machinery', 'Vehicles', 'Chemicals'], neighbours: ['Chile', 'Bolivia', 'Paraguay', 'Brazil', 'Uruguay'], tradeAgreements: ['MERCOSUR', 'EU-MERCOSUR'], seaPorts: [{ unLoCode: 'ARBUE', name: 'Buenos Aires', type: 'sea', coordinates: { lat: -34.6, lng: -58.37 }, throughput: '1.5M TEU' }, { unLoCode: 'ARBHI', name: 'Bahía Blanca', type: 'sea', coordinates: { lat: -38.8, lng: -62.27 }, throughput: '400K TEU' }, { unLoCode: 'ARROS', name: 'Rosario', type: 'river', coordinates: { lat: -32.95, lng: -60.65 }, throughput: '6M tons' }], airports: [{ unLoCode: 'SAEZ', name: 'Buenos Aires Airport', type: 'air', coordinates: { lat: -34.82, lng: -58.54 }, throughput: '200K tons' }], dryPorts: [] },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲', region: 'Asia', capital: 'Yerevan', currency: 'Dram', language: 'Armenian', timezone: 'UTC+4', coastline: 'Landlocked', population: '3M', gdp: '$14B', exports: ['Copper', 'Gold', 'Alcohol'], imports: ['Petroleum', 'Food', 'Machinery'], neighbours: ['Georgia', 'Azerbaijan', 'Iran', 'Turkey'], tradeAgreements: ['EAEU', 'WTO', 'EU Partnership'], seaPorts: [], airports: [{ unLoCode: 'UDYZ', name: 'Yerevan Airport', type: 'air', coordinates: { lat: 40.15, lng: 44.4 }, throughput: '30K tons' }], dryPorts: [{ unLoCode: 'AMEVN', name: 'Yerevan Dry Port', type: 'dry', coordinates: { lat: 40.18, lng: 44.52 } }] },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', region: 'Oceania', capital: 'Canberra', currency: 'Australian Dollar', language: 'English', timezone: 'UTC+8 to +11', coastline: '25,760 km', population: '26M', gdp: '$1.33T', exports: ['Iron Ore', 'Coal', 'Gold', 'Natural Gas'], imports: ['Machinery', 'Vehicles', 'Electronics'], neighbours: [], tradeAgreements: ['AANZFTA', 'CPTPP', 'RCEP', 'Australia-US FTA'], seaPorts: [{ unLoCode: 'AUSYD', name: 'Sydney', type: 'sea', coordinates: { lat: -33.85, lng: 151.22 }, throughput: '2.6M TEU' }, { unLoCode: 'AUMEL', name: 'Melbourne', type: 'sea', coordinates: { lat: -37.83, lng: 144.97 }, throughput: '3.2M TEU' }, { unLoCode: 'AUBNE', name: 'Brisbane', type: 'sea', coordinates: { lat: -27.38, lng: 153.12 }, throughput: '1.4M TEU' }, { unLoCode: 'AUHED', name: 'Port Hedland', type: 'sea', coordinates: { lat: -20.32, lng: 118.58 }, throughput: '550M tons' }], airports: [{ unLoCode: 'YSSY', name: 'Sydney Airport', type: 'air', coordinates: { lat: -33.95, lng: 151.18 }, throughput: '500K tons' }, { unLoCode: 'YMML', name: 'Melbourne Airport', type: 'air', coordinates: { lat: -37.67, lng: 144.84 }, throughput: '450K tons' }], dryPorts: [] },
  { code: 'AT', name: 'Austria', flag: '🇦🇹', region: 'Europe', capital: 'Vienna', currency: 'Euro', language: 'German', timezone: 'UTC+1', coastline: 'Landlocked', population: '9M', gdp: '$433B', exports: ['Machinery', 'Vehicles', 'Chemicals'], imports: ['Machinery', 'Vehicles', 'Chemicals'], neighbours: ['Germany', 'Czech Republic', 'Slovakia', 'Hungary', 'Slovenia', 'Italy', 'Switzerland', 'Liechtenstein'], tradeAgreements: ['EU Single Market', 'EEA', 'CETA'], seaPorts: [], airports: [{ unLoCode: 'LOWW', name: 'Vienna Airport', type: 'air', coordinates: { lat: 48.11, lng: 16.57 }, throughput: '300K tons' }], dryPorts: [{ unLoCode: 'ATVIE', name: 'Vienna Port', type: 'river', coordinates: { lat: 48.21, lng: 16.37 }, throughput: '450K TEU' }] },
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', region: 'Asia', capital: 'Baku', currency: 'Manat', language: 'Azerbaijani', timezone: 'UTC+4', coastline: '713 km (Caspian)', population: '10M', gdp: '$55B', exports: ['Oil', 'Natural Gas', 'Cotton'], imports: ['Machinery', 'Food', 'Vehicles'], neighbours: ['Russia', 'Georgia', 'Armenia', 'Iran', 'Turkey'], tradeAgreements: ['WTO', 'GUAM', 'BSEC'], seaPorts: [{ unLoCode: 'AZBAK', name: 'Baku', type: 'sea', coordinates: { lat: 40.37, lng: 49.83 }, throughput: '600K TEU' }], airports: [{ unLoCode: 'UBBB', name: 'Baku Airport', type: 'air', coordinates: { lat: 40.47, lng: 50.05 }, throughput: '100K tons' }], dryPorts: [] },
  // B
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸', region: 'Caribbean', capital: 'Nassau', currency: 'Bahamian Dollar', language: 'English', timezone: 'UTC-5', coastline: '3,542 km', population: '393K', gdp: '$13B', exports: ['Petroleum', 'Seafood', 'Chemicals'], imports: ['Food', 'Machinery', 'Vehicles'], neighbours: [], tradeAgreements: ['CARICOM', 'EPA'], seaPorts: [{ unLoCode: 'BSNAS', name: 'Nassau', type: 'sea', coordinates: { lat: 25.08, lng: -77.35 }, throughput: '3.5M cruise' }, { unLoCode: 'BSFPO', name: 'Freeport', type: 'sea', coordinates: { lat: 26.52, lng: -78.7 }, throughput: '1.8M TEU' }], airports: [{ unLoCode: 'MYNN', name: 'Nassau Airport', type: 'air', coordinates: { lat: 25.04, lng: -77.47 } }], dryPorts: [] },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭', region: 'Middle East', capital: 'Manama', currency: 'Bahraini Dinar', language: 'Arabic', timezone: 'UTC+3', coastline: '161 km', population: '1.7M', gdp: '$39B', exports: ['Petroleum', 'Aluminum', 'Textiles'], imports: ['Machinery', 'Food', 'Chemicals'], neighbours: ['Saudi Arabia', 'Qatar'], tradeAgreements: ['GCC', 'GAFTA', 'US-Bahrain FTA'], seaPorts: [{ unLoCode: 'BHBAH', name: 'Bahrain', type: 'sea', coordinates: { lat: 26.23, lng: 50.6 }, throughput: '600K TEU' }], airports: [{ unLoCode: 'OBBI', name: 'Bahrain Airport', type: 'air', coordinates: { lat: 26.27, lng: 50.63 }, throughput: '80K tons' }], dryPorts: [] },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', region: 'Asia', capital: 'Dhaka', currency: 'Taka', language: 'Bengali', timezone: 'UTC+6', coastline: '580 km', population: '165M', gdp: '$355B', exports: ['Garments', 'Jute', 'Tea', 'Seafood'], imports: ['Machinery', 'Food', 'Petroleum'], neighbours: ['India', 'Myanmar'], tradeAgreements: ['SAFTA', 'APTA', 'BIMSTEC'], seaPorts: [{ unLoCode: 'BDCGP', name: 'Chittagong', type: 'sea', coordinates: { lat: 22.32, lng: 91.82 }, throughput: '3.2M TEU' }, { unLoCode: 'BDMGL', name: 'Mongla', type: 'sea', coordinates: { lat: 22.47, lng: 89.6 }, throughput: '600K TEU' }], airports: [{ unLoCode: 'VGHS', name: 'Dhaka Airport', type: 'air', coordinates: { lat: 23.84, lng: 90.4 }, throughput: '150K tons' }], dryPorts: [{ unLoCode: 'BDDAC', name: 'Dhaka ICD', type: 'dry', coordinates: { lat: 23.81, lng: 90.41 }, throughput: '400K TEU' }] },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧', region: 'Caribbean', capital: 'Bridgetown', currency: 'Barbados Dollar', language: 'English', timezone: 'UTC-4', coastline: '97 km', population: '287K', gdp: '$5.5B', exports: ['Sugar', 'Molasses', 'Rum'], imports: ['Food', 'Machinery'], neighbours: [], tradeAgreements: ['CARICOM', 'EPA'], seaPorts: [{ unLoCode: 'BBBGI', name: 'Bridgetown', type: 'sea', coordinates: { lat: 13.1, lng: -59.62 }, throughput: '100K TEU' }], airports: [{ unLoCode: 'TBPB', name: 'Grantley Adams Airport', type: 'air', coordinates: { lat: 13.07, lng: -59.49 } }], dryPorts: [] },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾', region: 'Europe', capital: 'Minsk', currency: 'Belarusian Ruble', language: 'Belarusian, Russian', timezone: 'UTC+3', coastline: 'Landlocked', population: '9.4M', gdp: '$60B', exports: ['Machinery', 'Chemicals', 'Food'], imports: ['Natural Gas', 'Oil', 'Machinery'], neighbours: ['Russia', 'Ukraine', 'Poland', 'Lithuania', 'Latvia'], tradeAgreements: ['EAEU', 'CISFTA'], seaPorts: [], airports: [{ unLoCode: 'UMMS', name: 'Minsk Airport', type: 'air', coordinates: { lat: 53.88, lng: 28.03 }, throughput: '50K tons' }], dryPorts: [{ unLoCode: 'BYMSQ', name: 'Minsk Dry Port', type: 'dry', coordinates: { lat: 53.9, lng: 27.57 } }] },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪', region: 'Europe', capital: 'Brussels', currency: 'Euro', language: 'Dutch, French, German', timezone: 'UTC+1', coastline: '66 km', population: '11.5M', gdp: '$533B', exports: ['Machinery', 'Chemicals', 'Diamonds'], imports: ['Machinery', 'Chemicals', 'Diamonds'], neighbours: ['Netherlands', 'Germany', 'Luxembourg', 'France'], tradeAgreements: ['EU Single Market', 'EEA', 'Benelux', 'CETA'], seaPorts: [{ unLoCode: 'BEANR', name: 'Antwerp', type: 'sea', coordinates: { lat: 51.26, lng: 4.4 }, throughput: '12.5M TEU' }, { unLoCode: 'BEBRU', name: 'Zeebrugge', type: 'sea', coordinates: { lat: 51.33, lng: 3.2 }, throughput: '3.2M TEU' }], airports: [{ unLoCode: 'EBBR', name: 'Brussels Airport', type: 'air', coordinates: { lat: 50.9, lng: 4.48 }, throughput: '700K tons' }, { unLoCode: 'EBLG', name: 'Liège Airport', type: 'air', coordinates: { lat: 50.64, lng: 5.45 }, throughput: '900K tons' }], dryPorts: [] },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿', region: 'Central America', capital: 'Belmopan', currency: 'Belize Dollar', language: 'English', timezone: 'UTC-6', coastline: '386 km', population: '397K', gdp: '$1.7B', exports: ['Sugar', 'Bananas', 'Citrus'], imports: ['Food', 'Machinery'], neighbours: ['Mexico', 'Guatemala'], tradeAgreements: ['CARICOM', 'SICA', 'EPA'], seaPorts: [{ unLoCode: 'BZBZE', name: 'Belize City', type: 'sea', coordinates: { lat: 17.45, lng: -88.18 }, throughput: '50K TEU' }], airports: [{ unLoCode: 'MZBZ', name: 'Belize Airport', type: 'air', coordinates: { lat: 17.54, lng: -88.31 } }], dryPorts: [] },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯', region: 'Africa', capital: 'Porto-Novo', currency: 'CFA Franc', language: 'French', timezone: 'UTC+1', coastline: '121 km', population: '12M', gdp: '$16B', exports: ['Cotton', 'Cashews', 'Palm Oil'], imports: ['Food', 'Machinery'], neighbours: ['Togo', 'Burkina Faso', 'Niger', 'Nigeria'], tradeAgreements: ['ECOWAS', 'AfCFTA', 'EPA'], seaPorts: [{ unLoCode: 'BJCOO', name: 'Cotonou', type: 'sea', coordinates: { lat: 6.35, lng: 2.43 }, throughput: '500K TEU' }], airports: [{ unLoCode: 'DBBB', name: 'Cotonou Airport', type: 'air', coordinates: { lat: 6.36, lng: 2.38 } }], dryPorts: [] },
  { code: 'BT', name: 'Bhutan', flag: '🇧🇹', region: 'Asia', capital: 'Thimphu', currency: 'Ngultrum', language: 'Dzongkha', timezone: 'UTC+6', coastline: 'Landlocked', population: '771K', gdp: '$2.5B', exports: ['Electricity', 'Ferrosilicon'], imports: ['Fuel', 'Machinery', 'Food'], neighbours: ['India', 'China'], tradeAgreements: ['SAFTA', 'Bhutan-India Trade'], seaPorts: [], airports: [{ unLoCode: 'VQPR', name: 'Paro Airport', type: 'air', coordinates: { lat: 27.41, lng: 89.42 } }], dryPorts: [{ unLoCode: 'BTTHI', name: 'Phuentsholing', type: 'dry', coordinates: { lat: 26.85, lng: 89.38 } }] },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴', region: 'South America', capital: 'Sucre', currency: 'Boliviano', language: 'Spanish', timezone: 'UTC-4', coastline: 'Landlocked', population: '12M', gdp: '$37B', exports: ['Natural Gas', 'Soybeans', 'Zinc', 'Gold'], imports: ['Machinery', 'Vehicles', 'Fuel'], neighbours: ['Brazil', 'Paraguay', 'Argentina', 'Chile', 'Peru'], tradeAgreements: ['MERCOSUR', 'CAN', 'ALBA'], seaPorts: [], airports: [{ unLoCode: 'SLCB', name: 'La Paz Airport', type: 'air', coordinates: { lat: -16.51, lng: -68.19 }, throughput: '30K tons' }, { unLoCode: 'SLVR', name: 'Santa Cruz Airport', type: 'air', coordinates: { lat: -17.64, lng: -63.14 }, throughput: '40K tons' }], dryPorts: [{ unLoCode: 'BOSCZ', name: 'Santa Cruz ICD', type: 'dry', coordinates: { lat: -17.78, lng: -63.18 } }] },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', region: 'Europe', capital: 'Sarajevo', currency: 'Mark', language: 'Bosnian, Serbian, Croatian', timezone: 'UTC+1', coastline: '20 km', population: '3.3M', gdp: '$20B', exports: ['Aluminum', 'Steel', 'Furniture'], imports: ['Machinery', 'Food', 'Chemicals'], neighbours: ['Croatia', 'Serbia', 'Montenegro'], tradeAgreements: ['CEFTA', 'EU Stabilization'], seaPorts: [], airports: [{ unLoCode: 'LQSA', name: 'Sarajevo Airport', type: 'air', coordinates: { lat: 43.82, lng: 18.33 } }], dryPorts: [] },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼', region: 'Africa', capital: 'Gaborone', currency: 'Pula', language: 'English, Setswana', timezone: 'UTC+2', coastline: 'Landlocked', population: '2.3M', gdp: '$18B', exports: ['Diamonds', 'Copper', 'Gold'], imports: ['Food', 'Machinery', 'Fuel'], neighbours: ['South Africa', 'Namibia', 'Zimbabwe', 'Zambia'], tradeAgreements: ['SADC', 'SACU', 'AfCFTA'], seaPorts: [], airports: [{ unLoCode: 'FBSK', name: 'Gaborone Airport', type: 'air', coordinates: { lat: -24.56, lng: 25.92 } }], dryPorts: [{ unLoCode: 'BWGBE', name: 'Gaborone ICD', type: 'dry', coordinates: { lat: -24.63, lng: 25.92 } }] },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', region: 'South America', capital: 'Brasília', currency: 'Real', language: 'Portuguese', timezone: 'UTC-2 to -5', coastline: '7,491 km', population: '213M', gdp: '$1.44T', exports: ['Soybeans', 'Iron Ore', 'Crude Oil', 'Sugar', 'Coffee'], imports: ['Machinery', 'Electronics', 'Vehicles'], neighbours: ['French Guiana', 'Suriname', 'Guyana', 'Venezuela', 'Colombia', 'Peru', 'Bolivia', 'Paraguay', 'Argentina', 'Uruguay'], tradeAgreements: ['MERCOSUR', 'EU-MERCOSUR', 'BRICS'], seaPorts: [{ unLoCode: 'BRSSZ', name: 'Santos', type: 'sea', coordinates: { lat: -23.95, lng: -46.3 }, throughput: '4.8M TEU' }, { unLoCode: 'BRPNG', name: 'Paranaguá', type: 'sea', coordinates: { lat: -25.52, lng: -48.52 }, throughput: '1.6M TEU' }, { unLoCode: 'BRRIG', name: 'Rio Grande', type: 'sea', coordinates: { lat: -32.03, lng: -52.1 }, throughput: '700K TEU' }, { unLoCode: 'BRMAO', name: 'Manaus', type: 'river', coordinates: { lat: -3.13, lng: -60.03 }, throughput: '800K TEU' }], airports: [{ unLoCode: 'SBGR', name: 'São Paulo Airport', type: 'air', coordinates: { lat: -23.44, lng: -46.47 }, throughput: '600K tons' }, { unLoCode: 'SBGL', name: 'Rio Airport', type: 'air', coordinates: { lat: -22.81, lng: -43.25 }, throughput: '200K tons' }], dryPorts: [] },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳', region: 'Asia', capital: 'Bandar Seri Begawan', currency: 'Brunei Dollar', language: 'Malay', timezone: 'UTC+8', coastline: '161 km', population: '437K', gdp: '$12B', exports: ['Petroleum', 'Natural Gas'], imports: ['Machinery', 'Food', 'Vehicles'], neighbours: ['Malaysia'], tradeAgreements: ['ASEAN', 'RCEP', 'CPTPP'], seaPorts: [{ unLoCode: 'BNBWN', name: 'Muara', type: 'sea', coordinates: { lat: 5.02, lng: 115.07 }, throughput: '200K TEU' }], airports: [{ unLoCode: 'WBSB', name: 'Brunei Airport', type: 'air', coordinates: { lat: 4.94, lng: 114.93 } }], dryPorts: [] },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', region: 'Europe', capital: 'Sofia', currency: 'Lev', language: 'Bulgarian', timezone: 'UTC+2', coastline: '354 km', population: '6.9M', gdp: '$69B', exports: ['Machinery', 'Chemicals', 'Metals'], imports: ['Machinery', 'Fuel', 'Chemicals'], neighbours: ['Romania', 'Serbia', 'North Macedonia', 'Greece', 'Turkey'], tradeAgreements: ['EU Single Market', 'EEA', 'CETA'], seaPorts: [{ unLoCode: 'BGVAR', name: 'Varna', type: 'sea', coordinates: { lat: 43.2, lng: 27.92 }, throughput: '400K TEU' }, { unLoCode: 'BGBGS', name: 'Burgas', type: 'sea', coordinates: { lat: 42.49, lng: 27.47 }, throughput: '300K TEU' }], airports: [{ unLoCode: 'LBSF', name: 'Sofia Airport', type: 'air', coordinates: { lat: 42.69, lng: 23.41 }, throughput: '40K tons' }], dryPorts: [] },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', region: 'Africa', capital: 'Ouagadougou', currency: 'CFA Franc', language: 'French', timezone: 'UTC', coastline: 'Landlocked', population: '21.5M', gdp: '$17B', exports: ['Gold', 'Cotton', 'Shea Butter'], imports: ['Food', 'Machinery', 'Fuel'], neighbours: ['Mali', 'Niger', 'Benin', 'Togo', 'Ghana', 'Ivory Coast'], tradeAgreements: ['ECOWAS', 'AfCFTA', 'WAEMU'], seaPorts: [], airports: [{ unLoCode: 'DFFD', name: 'Ouagadougou Airport', type: 'air', coordinates: { lat: 12.35, lng: -1.51 } }], dryPorts: [{ unLoCode: 'BFOUA', name: 'Ouagadougou ICD', type: 'dry', coordinates: { lat: 12.37, lng: -1.53 } }] },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮', region: 'Africa', capital: 'Gitega', currency: 'Burundi Franc', language: 'Kirundi, French', timezone: 'UTC+2', coastline: 'Landlocked', population: '11.9M', gdp: '$3.1B', exports: ['Coffee', 'Tea', 'Gold'], imports: ['Food', 'Machinery', 'Fuel'], neighbours: ['Rwanda', 'Tanzania', 'DR Congo'], tradeAgreements: ['EAC', 'AfCFTA', 'COMESA'], seaPorts: [], airports: [{ unLoCode: 'HBBA', name: 'Bujumbura Airport', type: 'air', coordinates: { lat: -3.32, lng: 29.32 } }], dryPorts: [{ unLoCode: 'BIBJM', name: 'Bujumbura ICD', type: 'dry', coordinates: { lat: -3.38, lng: 29.36 } }] },
  // C
  { code: 'KH', name: 'Cambodia', flag: '🇰🇭', region: 'Asia', capital: 'Phnom Penh', currency: 'Riel', language: 'Khmer', timezone: 'UTC+7', coastline: '443 km', population: '17M', gdp: '$27B', exports: ['Garments', 'Rice', 'Rubber', 'Footwear'], imports: ['Machinery', 'Fuel', 'Textiles'], neighbours: ['Thailand', 'Laos', 'Vietnam'], tradeAgreements: ['ASEAN', 'RCEP', 'EBA EU'], seaPorts: [{ unLoCode: 'KHSIH', name: 'Sihanoukville', type: 'sea', coordinates: { lat: 10.63, lng: 103.52 }, throughput: '900K TEU' }, { unLoCode: 'KHPNH', name: 'Phnom Penh', type: 'river', coordinates: { lat: 11.58, lng: 104.92 }, throughput: '300K TEU' }], airports: [{ unLoCode: 'VDPP', name: 'Phnom Penh Airport', type: 'air', coordinates: { lat: 11.55, lng: 104.84 }, throughput: '50K tons' }], dryPorts: [] },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲', region: 'Africa', capital: 'Yaoundé', currency: 'CFA Franc', language: 'French, English', timezone: 'UTC+1', coastline: '402 km', population: '26M', gdp: '$39B', exports: ['Petroleum', 'Cocoa', 'Timber', 'Coffee'], imports: ['Machinery', 'Food', 'Fuel'], neighbours: ['Nigeria', 'Chad', 'CAR', 'Congo', 'Gabon', 'Equatorial Guinea'], tradeAgreements: ['CEMAC', 'AfCFTA', 'EPA'], seaPorts: [{ unLoCode: 'CMDLA', name: 'Douala', type: 'sea', coordinates: { lat: 4.02, lng: 9.72 }, throughput: '400K TEU' }, { unLoCode: 'CMKRK', name: 'Kribi', type: 'sea', coordinates: { lat: 2.94, lng: 9.91 }, throughput: '300K TEU' }], airports: [{ unLoCode: 'FKKY', name: 'Douala Airport', type: 'air', coordinates: { lat: 4.01, lng: 9.72 }, throughput: '50K tons' }], dryPorts: [] },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', region: 'North America', capital: 'Ottawa', currency: 'Canadian Dollar', language: 'English, French', timezone: 'UTC-3.5 to -8', coastline: '202,080 km', population: '38.5M', gdp: '$1.99T', exports: ['Crude Oil', 'Cars', 'Gold', 'Lumber'], imports: ['Vehicles', 'Machinery', 'Electronics'], neighbours: ['United States'], tradeAgreements: ['CUSMA/USMCA', 'CPTPP', 'CETA', 'Canada-UK TCA'], seaPorts: [{ unLoCode: 'CAVAN', name: 'Vancouver', type: 'sea', coordinates: { lat: 49.28, lng: -123.12 }, throughput: '3.5M TEU' }, { unLoCode: 'CAMTR', name: 'Montreal', type: 'sea', coordinates: { lat: 45.5, lng: -73.57 }, throughput: '1.8M TEU' }, { unLoCode: 'CAPTO', name: 'Prince Rupert', type: 'sea', coordinates: { lat: 54.31, lng: -130.32 }, throughput: '1.2M TEU' }], airports: [{ unLoCode: 'CYYZ', name: 'Toronto Airport', type: 'air', coordinates: { lat: 43.68, lng: -79.63 }, throughput: '400K tons' }, { unLoCode: 'CYUL', name: 'Montreal Airport', type: 'air', coordinates: { lat: 45.47, lng: -73.74 }, throughput: '250K tons' }], dryPorts: [] },
  { code: 'CV', name: 'Cape Verde', flag: '🇨🇻', region: 'Africa', capital: 'Praia', currency: 'Cape Verde Escudo', language: 'Portuguese', timezone: 'UTC-1', coastline: '965 km', population: '556K', gdp: '$1.9B', exports: ['Fish', 'Shoes', 'Clothing'], imports: ['Food', 'Fuel', 'Machinery'], neighbours: [], tradeAgreements: ['ECOWAS', 'AfCFTA', 'EPA'], seaPorts: [{ unLoCode: 'CVRAI', name: 'Praia', type: 'sea', coordinates: { lat: 14.92, lng: -23.52 }, throughput: '100K TEU' }, { unLoCode: 'CVMIN', name: 'Mindelo', type: 'sea', coordinates: { lat: 16.88, lng: -25.0 } }], airports: [{ unLoCode: 'GVNP', name: 'Praia Airport', type: 'air', coordinates: { lat: 14.93, lng: -23.49 } }], dryPorts: [] },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫', region: 'Africa', capital: 'Bangui', currency: 'CFA Franc', language: 'French, Sango', timezone: 'UTC+1', coastline: 'Landlocked', population: '4.8M', gdp: '$2.5B', exports: ['Diamonds', 'Timber', 'Cotton'], imports: ['Food', 'Machinery', 'Fuel'], neighbours: ['Chad', 'Sudan', 'South Sudan', 'Congo', 'Cameroon'], tradeAgreements: ['CEMAC', 'AfCFTA'], seaPorts: [], airports: [{ unLoCode: 'FEFF', name: 'Bangui Airport', type: 'air', coordinates: { lat: 4.4, lng: 18.52 } }], dryPorts: [{ unLoCode: 'CFBGF', name: 'Bangui ICD', type: 'dry', coordinates: { lat: 4.37, lng: 18.57 } }] },
  { code: 'TD', name: 'Chad', flag: '🇹🇩', region: 'Africa', capital: "N'Djamena", currency: 'CFA Franc', language: 'French, Arabic', timezone: 'UTC+1', coastline: 'Landlocked', population: '16M', gdp: '$11B', exports: ['Petroleum', 'Gold', 'Cotton'], imports: ['Food', 'Machinery', 'Fuel'], neighbours: ['Libya', 'Sudan', 'CAR', 'Cameroon', 'Nigeria', 'Niger'], tradeAgreements: ['CEMAC', 'AfCFTA', 'LCBC'], seaPorts: [], airports: [{ unLoCode: 'FTTJ', name: "N'Djamena Airport", type: 'air', coordinates: { lat: 12.13, lng: 15.03 } }], dryPorts: [{ unLoCode: 'TDNDA', name: "N'Djamena ICD", type: 'dry', coordinates: { lat: 12.1, lng: 15.05 } }] },
  { code: 'CL', name: 'Chile', flag: '🇨🇱', region: 'South America', capital: 'Santiago', currency: 'Peso', language: 'Spanish', timezone: 'UTC-4 to -6', coastline: '6,435 km', population: '19M', gdp: '$282B', exports: ['Copper', 'Fruit', 'Fish', 'Wood Pulp'], imports: ['Petroleum', 'Machinery', 'Vehicles'], neighbours: ['Peru', 'Bolivia', 'Argentina'], tradeAgreements: ['Pacific Alliance', 'Chile-US FTA', 'CPTPP', 'Chile-China FTA'], seaPorts: [{ unLoCode: 'CLSAI', name: 'San Antonio', type: 'sea', coordinates: { lat: -33.6, lng: -71.62 }, throughput: '1.4M TEU' }, { unLoCode: 'CLVAL', name: 'Valparaíso', type: 'sea', coordinates: { lat: -33.05, lng: -71.62 }, throughput: '900K TEU' }], airports: [{ unLoCode: 'SCEL', name: 'Santiago Airport', type: 'air', coordinates: { lat: -33.39, lng: -70.79 }, throughput: '200K tons' }], dryPorts: [] },
  { code: 'CN', name: 'China', flag: '🇨🇳', region: 'Asia', capital: 'Beijing', currency: 'Yuan', language: 'Mandarin Chinese', timezone: 'UTC+8', coastline: '14,500 km', population: '1.41B', gdp: '$18T', exports: ['Electronics', 'Machinery', 'Textiles', 'Steel'], imports: ['Electronics', 'Oil', 'Machinery'], neighbours: ['Russia', 'Mongolia', 'North Korea', 'Vietnam', 'Laos', 'Myanmar', 'India', 'Bhutan', 'Nepal', 'Pakistan', 'Afghanistan', 'Tajikistan', 'Kyrgyzstan', 'Kazakhstan'], tradeAgreements: ['RCEP', 'ASEAN-China FTA', 'Belt and Road', 'China-Pakistan FTA', 'China-Australia FTA'], seaPorts: [{ unLoCode: 'CNSHA', name: 'Shanghai', type: 'sea', coordinates: { lat: 31.36, lng: 121.59 }, throughput: '47M TEU' }, { unLoCode: 'CNSZX', name: 'Shenzhen', type: 'sea', coordinates: { lat: 22.48, lng: 113.91 }, throughput: '28M TEU' }, { unLoCode: 'CNNGB', name: 'Ningbo-Zhoushan', type: 'sea', coordinates: { lat: 29.87, lng: 121.54 }, throughput: '33M TEU' }, { unLoCode: 'CNQIN', name: 'Qingdao', type: 'sea', coordinates: { lat: 36.07, lng: 120.38 }, throughput: '23M TEU' }, { unLoCode: 'CNGZH', name: 'Guangzhou', type: 'sea', coordinates: { lat: 22.95, lng: 113.52 }, throughput: '24M TEU' }, { unLoCode: 'CNTXG', name: 'Tianjin', type: 'sea', coordinates: { lat: 38.98, lng: 117.78 }, throughput: '20M TEU' }], airports: [{ unLoCode: 'ZSSS', name: 'Shanghai Pudong Airport', type: 'air', coordinates: { lat: 31.14, lng: 121.81 }, throughput: '3.5M tons' }, { unLoCode: 'ZGGG', name: 'Guangzhou Airport', type: 'air', coordinates: { lat: 23.39, lng: 113.3 }, throughput: '2M tons' }], dryPorts: [] },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', region: 'South America', capital: 'Bogotá', currency: 'Peso', language: 'Spanish', timezone: 'UTC-5', coastline: '3,208 km', population: '51M', gdp: '$270B', exports: ['Petroleum', 'Coal', 'Coffee', 'Flowers'], imports: ['Machinery', 'Electronics', 'Vehicles'], neighbours: ['Panama', 'Venezuela', 'Brazil', 'Peru', 'Ecuador'], tradeAgreements: ['Pacific Alliance', 'US-Colombia TPA', 'EU-Colombia FTA', 'CAN'], seaPorts: [{ unLoCode: 'COCTG', name: 'Cartagena', type: 'sea', coordinates: { lat: 10.42, lng: -75.52 }, throughput: '2.5M TEU' }, { unLoCode: 'COBUN', name: 'Buenaventura', type: 'sea', coordinates: { lat: 3.88, lng: -77.07 }, throughput: '1M TEU' }, { unLoCode: 'COSMR', name: 'Santa Marta', type: 'sea', coordinates: { lat: 11.25, lng: -74.22 }, throughput: '500K TEU' }], airports: [{ unLoCode: 'SKBO', name: 'Bogotá Airport', type: 'air', coordinates: { lat: 4.7, lng: -74.15 }, throughput: '700K tons' }], dryPorts: [] },
  { code: 'KM', name: 'Comoros', flag: '🇰🇲', region: 'Africa', capital: 'Moroni', currency: 'Comorian Franc', language: 'Comorian, Arabic, French', timezone: 'UTC+3', coastline: '340 km', population: '870K', gdp: '$1.2B', exports: ['Vanilla', 'Ylang-ylang', 'Cloves'], imports: ['Food', 'Fuel', 'Machinery'], neighbours: [], tradeAgreements: ['AfCFTA', 'IOC', 'EPA'], seaPorts: [{ unLoCode: 'KMMNI', name: 'Moroni', type: 'sea', coordinates: { lat: -11.7, lng: 43.26 } }], airports: [{ unLoCode: 'FMCH', name: 'Moroni Airport', type: 'air', coordinates: { lat: -11.53, lng: 43.27 } }], dryPorts: [] },
  { code: 'CG', name: 'Congo', flag: '🇨🇬', region: 'Africa', capital: 'Brazzaville', currency: 'CFA Franc', language: 'French', timezone: 'UTC+1', coastline: '169 km', population: '5.5M', gdp: '$10B', exports: ['Petroleum', 'Wood', 'Potash'], imports: ['Food', 'Machinery', 'Fuel'], neighbours: ['Gabon', 'Cameroon', 'CAR', 'DR Congo', 'Angola'], tradeAgreements: ['CEMAC', 'AfCFTA', 'EPA'], seaPorts: [{ unLoCode: 'CGPNR', name: 'Pointe-Noire', type: 'sea', coordinates: { lat: -4.78, lng: 11.85 }, throughput: '350K TEU' }], airports: [{ unLoCode: 'FCBB', name: 'Brazzaville Airport', type: 'air', coordinates: { lat: -4.26, lng: 15.25 } }], dryPorts: [] },
  { code: 'CD', name: 'DR Congo', flag: '🇨🇩', region: 'Africa', capital: 'Kinshasa', currency: 'Congolese Franc', language: 'French', timezone: 'UTC+1 to +2', coastline: '37 km', population: '89M', gdp: '$44B', exports: ['Copper', 'Cobalt', 'Diamonds', 'Gold'], imports: ['Food', 'Machinery', 'Fuel'], neighbours: ['Congo', 'CAR', 'South Sudan', 'Uganda', 'Rwanda', 'Burundi', 'Tanzania', 'Zambia', 'Angola'], tradeAgreements: ['COMESA', 'AfCFTA', 'SADC'], seaPorts: [{ unLoCode: 'CDFIY', name: 'Matadi', type: 'sea', coordinates: { lat: -5.82, lng: 13.47 }, throughput: '100K TEU' }, { unLoCode: 'CDBMA', name: 'Boma', type: 'sea', coordinates: { lat: -5.85, lng: 13.07 } }], airports: [{ unLoCode: 'FZAA', name: 'Kinshasa Airport', type: 'air', coordinates: { lat: -4.39, lng: 15.45 }, throughput: '80K tons' }], dryPorts: [{ unLoCode: 'CDFIH', name: 'Kinshasa ICD', type: 'dry', coordinates: { lat: -4.33, lng: 15.31 } }] },
  { code: 'CK', name: 'Cook Islands', flag: '🇨🇰', region: 'Oceania', capital: 'Avarua', currency: 'New Zealand Dollar', language: 'English, Cook Islands Māori', timezone: 'UTC-10', coastline: '120 km', population: '17K', gdp: '$300M', exports: ['Tourism', 'Pearls', 'Papaya'], imports: ['Food', 'Fuel', 'Machinery'], neighbours: [], tradeAgreements: ['PACER Plus'], seaPorts: [{ unLoCode: 'CKAVV', name: 'Avarua', type: 'sea', coordinates: { lat: -21.21, lng: -159.77 } }], airports: [{ unLoCode: 'NCRG', name: 'Rarotonga Airport', type: 'air', coordinates: { lat: -21.2, lng: -159.81 } }], dryPorts: [] },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', region: 'Central America', capital: 'San José', currency: 'Colón', language: 'Spanish', timezone: 'UTC-6', coastline: '1,290 km', population: '5.1M', gdp: '$64B', exports: ['Bananas', 'Pineapples', 'Medical Devices', 'Coffee'], imports: ['Machinery', 'Electronics', 'Fuel'], neighbours: ['Nicaragua', 'Panama'], tradeAgreements: ['CAFTA-DR', 'Costa Rica-EU FTA', 'Pacific Alliance'], seaPorts: [{ unLoCode: 'CRLIO', name: 'Limón', type: 'sea', coordinates: { lat: 10.0, lng: -83.03 }, throughput: '400K TEU' }, { unLoCode: 'CRPCL', name: 'Caldera', type: 'sea', coordinates: { lat: 9.92, lng: -84.77 }, throughput: '300K TEU' }], airports: [{ unLoCode: 'MROC', name: 'San José Airport', type: 'air', coordinates: { lat: 9.99, lng: -84.2 }, throughput: '100K tons' }], dryPorts: [] },
  { code: 'CI', name: 'Ivory Coast', flag: '🇨🇮', region: 'Africa', capital: 'Yamoussoukro', currency: 'CFA Franc', language: 'French', timezone: 'UTC', coastline: '515 km', population: '26M', gdp: '$62B', exports: ['Cocoa', 'Coffee', 'Gold', 'Petroleum'], imports: ['Food', 'Machinery', 'Fuel'], neighbours: ['Mali', 'Burkina Faso', 'Ghana', 'Liberia', 'Guinea'], tradeAgreements: ['ECOWAS', 'AfCFTA', 'EPA'], seaPorts: [{ unLoCode: 'CIABJ', name: 'Abidjan', type: 'sea', coordinates: { lat: 5.32, lng: -4.02 }, throughput: '1.2M TEU' }, { unLoCode: 'CISAN', name: 'San Pedro', type: 'sea', coordinates: { lat: 4.75, lng: -6.63 }, throughput: '500K TEU' }], airports: [{ unLoCode: 'DIAP', name: 'Abidjan Airport', type: 'air', coordinates: { lat: 5.26, lng: -3.93 }, throughput: '100K tons' }], dryPorts: [] },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷', region: 'Europe', capital: 'Zagreb', currency: 'Euro', language: 'Croatian', timezone: 'UTC+1', coastline: '5,835 km', population: '4M', gdp: '$57B', exports: ['Machinery', 'Chemicals', 'Food'], imports: ['Machinery', 'Fuel', 'Chemicals'], neighbours: ['Slovenia', 'Hungary', 'Serbia', 'Bosnia', 'Montenegro'], tradeAgreements: ['EU Single Market', 'EEA', 'CETA'], seaPorts: [{ unLoCode: 'HRRJK', name: 'Rijeka', type: 'sea', coordinates: { lat: 45.33, lng: 14.43 }, throughput: '350K TEU' }, { unLoCode: 'HRSPU', name: 'Split', type: 'sea', coordinates: { lat: 43.51, lng: 16.44 }, throughput: '150K TEU' }], airports: [{ unLoCode: 'LDZA', name: 'Zagreb Airport', type: 'air', coordinates: { lat: 45.74, lng: 16.07 }, throughput: '30K tons' }], dryPorts: [] },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', region: 'Caribbean', capital: 'Havana', currency: 'Cuban Peso', language: 'Spanish', timezone: 'UTC-5', coastline: '3,735 km', population: '11M', gdp: '$100B', exports: ['Nickel', 'Sugar', 'Tobacco', 'Medical Products'], imports: ['Food', 'Fuel', 'Machinery'], neighbours: [], tradeAgreements: ['CARICOM', 'ALBA', 'Cuba-EU'], seaPorts: [{ unLoCode: 'CUHAV', name: 'Havana', type: 'sea', coordinates: { lat: 23.13, lng: -82.35 }, throughput: '300K TEU' }, { unLoCode: 'CUMAR', name: 'Mariel', type: 'sea', coordinates: { lat: 22.99, lng: -82.75 }, throughput: '500K TEU' }], airports: [{ unLoCode: 'MUHA', name: 'Havana Airport', type: 'air', coordinates: { lat: 22.99, lng: -82.41 }, throughput: '50K tons' }], dryPorts: [] },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾', region: 'Europe', capital: 'Nicosia', currency: 'Euro', language: 'Greek, Turkish', timezone: 'UTC+2', coastline: '648 km', population: '1.2M', gdp: '$25B', exports: ['Pharmaceuticals', 'Citrus', 'Cheese'], imports: ['Fuel', 'Machinery', 'Food'], neighbours: [], tradeAgreements: ['EU Single Market', 'EEA', 'Cyprus-Egypt FTA'], seaPorts: [{ unLoCode: 'CYLMS', name: 'Limassol', type: 'sea', coordinates: { lat: 34.65, lng: 33.0 }, throughput: '600K TEU' }], airports: [{ unLoCode: 'LCLK', name: 'Larnaca Airport', type: 'air', coordinates: { lat: 34.88, lng: 33.63 }, throughput: '60K tons' }], dryPorts: [] },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', region: 'Europe', capital: 'Prague', currency: 'Czech Koruna', language: 'Czech', timezone: 'UTC+1', coastline: 'Landlocked', population: '10.7M', gdp: '$246B', exports: ['Machinery', 'Vehicles', 'Electronics'], imports: ['Machinery', 'Vehicles', 'Electronics'], neighbours: ['Germany', 'Poland', 'Slovakia', 'Austria'], tradeAgreements: ['EU Single Market', 'EEA', 'CETA'], seaPorts: [], airports: [{ unLoCode: 'LKPR', name: 'Prague Airport', type: 'air', coordinates: { lat: 50.1, lng: 14.26 }, throughput: '150K tons' }], dryPorts: [{ unLoCode: 'CZPRG', name: 'Prague ICD', type: 'dry', coordinates: { lat: 50.08, lng: 14.44 } }] },
  // D
  { code: 'DK', name: 'Denmark', flag: '🇩🇰', region: 'Europe', capital: 'Copenhagen', currency: 'Danish Krone', language: 'Danish', timezone: 'UTC+1', coastline: '7,314 km', population: '5.8M', gdp: '$340B', exports: ['Machinery', 'Pharmaceuticals', 'Meat'], imports: ['Machinery', 'Fuel', 'Chemicals'], neighbours: ['Germany'], tradeAgreements: ['EU Single Market', 'EEA', 'Nordic Council', 'CETA'], seaPorts: [{ unLoCode: 'DKCPH', name: 'Copenhagen', type: 'sea', coordinates: { lat: 55.71, lng: 12.62 }, throughput: '300K TEU' }, { unLoCode: 'DKAAR', name: 'Aarhus', type: 'sea', coordinates: { lat: 56.15, lng: 10.21 }, throughput: '600K TEU' }], airports: [{ unLoCode: 'EKCH', name: 'Copenhagen Airport', type: 'air', coordinates: { lat: 55.62, lng: 12.65 }, throughput: '400K tons' }], dryPorts: [] },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', region: 'Africa', capital: 'Djibouti', currency: 'Djibouti Franc', language: 'Arabic, French', timezone: 'UTC+3', coastline: '314 km', population: '988K', gdp: '$3.4B', exports: ['Re-exports', 'Salt', 'Animals'], imports: ['Food', 'Fuel', 'Machinery'], neighbours: ['Eritrea', 'Ethiopia', 'Somalia'], tradeAgreements: ['COMESA', 'AfCFTA', 'IGAD'], seaPorts: [{ unLoCode: 'DJDJI', name: 'Doraleh', type: 'sea', coordinates: { lat: 11.56, lng: 43.13 }, throughput: '1.5M TEU' }, { unLoCode: 'DJJIB', name: 'Djibouti', type: 'sea', coordinates: { lat: 11.59, lng: 43.14 }, throughput: '800K TEU' }], airports: [{ unLoCode: 'HDAM', name: 'Djibouti Airport', type: 'air', coordinates: { lat: 11.55, lng: 43.16 }, throughput: '30K tons' }], dryPorts: [] },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲', region: 'Caribbean', capital: 'Roseau', currency: 'East Caribbean Dollar', language: 'English', timezone: 'UTC-4', coastline: '148 km', population: '72K', gdp: '$550M', exports: ['Bananas', 'Soap', 'Citrus'], imports: ['Food', 'Machinery', 'Fuel'], neighbours: [], tradeAgreements: ['CARICOM', 'EPA', 'CSME'], seaPorts: [{ unLoCode: 'DMROS', name: 'Roseau', type: 'sea', coordinates: { lat: 15.3, lng: -61.39 } }], airports: [{ unLoCode: 'TDPD', name: 'Dominica Airport', type: 'air', coordinates: { lat: 15.54, lng: -61.3 } }], dryPorts: [] },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', region: 'Caribbean', capital: 'Santo Domingo', currency: 'Dominican Peso', language: 'Spanish', timezone: 'UTC-4', coastline: '1,288 km', population: '10.8M', gdp: '$94B', exports: ['Gold', 'Medical Instruments', 'Bananas'], imports: ['Food', 'Fuel', 'Machinery'], neighbours: ['Haiti'], tradeAgreements: ['CAFTA-DR', 'EPA', 'CARIFORUM'], seaPorts: [{ unLoCode: 'DOSDQ', name: 'Santo Domingo', type: 'sea', coordinates: { lat: 18.47, lng: -69.88 }, throughput: '400K TEU' }, { unLoCode: 'DOHAI', name: 'Haina', type: 'sea', coordinates: { lat: 18.42, lng: -70.02 }, throughput: '350K TEU' }], airports: [{ unLoCode: 'MDSD', name: 'Santo Domingo Airport', type: 'air', coordinates: { lat: 18.43, lng: -69.67 }, throughput: '100K tons' }], dryPorts: [] },
];

// Continue with remaining countries...
// This file can be extended with all 195 countries

export function getAllCountries() {
  return ALL_COUNTRIES;
}

export function getCountryByCode(code: string) {
  return ALL_COUNTRIES.find(c => c.code === code);
}

export function getCountriesByRegion(region: string) {
  return ALL_COUNTRIES.filter(c => c.region === region);
}

export function searchCountries(query: string) {
  const lower = query.toLowerCase();
  return ALL_COUNTRIES.filter(c => 
    c.name.toLowerCase().includes(lower) ||
    c.capital.toLowerCase().includes(lower) ||
    c.code.toLowerCase().includes(lower)
  );
}

export function getStatistics() {
  return {
    totalCountries: ALL_COUNTRIES.length,
    totalSeaPorts: ALL_COUNTRIES.reduce((sum, c) => sum + c.seaPorts.length, 0),
    totalAirports: ALL_COUNTRIES.reduce((sum, c) => sum + c.airports.length, 0),
    totalDryPorts: ALL_COUNTRIES.reduce((sum, c) => sum + c.dryPorts.length, 0),
    landlocked: ALL_COUNTRIES.filter(c => c.coastline === 'Landlocked').length,
  };
}
