// UN/LOCODE Port Data for Shiportrade.com
// Reference: https://unece.org/cefact/unlocode

export interface Port {
  unLoCode: string;           // 5-character UN/LOCODE
  name: string;               // Port name
  country: string;            // Country name
  countryCode: string;        // ISO 3166-1 alpha-2 country code
  region: string;             // Geographic region
  coordinates: {
    lat: number;
    lng: number;
  };
  portType: PortType[];
  facilities: string[];
  vesselTypes: string[];
  throughput?: string;        // Annual TEU (if applicable)
  timezone: string;
  status: 'active' | 'inactive' | 'limited';
}

export type PortType = 
  | 'Seaport'
  | 'River Port'
  | 'Inland Port'
  | 'Airport'
  | 'Dry Port'
  | 'Container Terminal'
  | 'RoRo Terminal'
  | 'Bulk Terminal'
  | 'Tanker Terminal'
  | 'Cruise Terminal'
  | 'Ferry Terminal'
  | 'Multi-Purpose';

export interface Country {
  code: string;               // ISO 3166-1 alpha-2
  name: string;
  region: string;
  hasCoastline: boolean;
  majorPorts: number;
}

export interface Region {
  id: string;
  name: string;
  description: string;
  countries: string[];
}

export const REGIONS: Region[] = [
  {
    id: 'asia',
    name: 'Asia',
    description: 'Major shipping hubs in East and Southeast Asia',
    countries: ['CN', 'JP', 'KR', 'TW', 'SG', 'MY', 'TH', 'VN', 'ID', 'PH', 'HK', 'AE', 'SA', 'IN', 'PK', 'BD', 'LK'],
  },
  {
    id: 'europe',
    name: 'Europe',
    description: 'Leading European container and bulk ports',
    countries: ['NL', 'BE', 'DE', 'GB', 'FR', 'ES', 'IT', 'GR', 'PL', 'SE', 'DK', 'FI', 'NO', 'PT', 'IE', 'RU', 'TR'],
  },
  {
    id: 'north-america',
    name: 'North America',
    description: 'Major US and Canadian gateway ports',
    countries: ['US', 'CA', 'MX'],
  },
  {
    id: 'south-america',
    name: 'South America',
    description: 'Key ports in Brazil, Argentina, Chile and others',
    countries: ['BR', 'AR', 'CL', 'CO', 'PE', 'EC', 'VE', 'UY'],
  },
  {
    id: 'africa',
    name: 'Africa',
    description: 'Growing port infrastructure across the continent',
    countries: ['ZA', 'EG', 'MA', 'NG', 'KE', 'TZ', 'GH', 'CI', 'SN', 'MZ', 'DZ', 'TN'],
  },
  {
    id: 'oceania',
    name: 'Oceania',
    description: 'Australian and Pacific Island ports',
    countries: ['AU', 'NZ', 'FJ', 'PG'],
  },
  {
    id: 'middle-east',
    name: 'Middle East',
    description: 'Strategic ports connecting Asia, Europe and Africa',
    countries: ['AE', 'SA', 'QA', 'OM', 'KW', 'BH', 'IQ', 'IR', 'JO', 'IL', 'LB'],
  },
];

export const COUNTRIES: Country[] = [
  // Asia
  { code: 'CN', name: 'China', region: 'Asia', hasCoastline: true, majorPorts: 34 },
  { code: 'JP', name: 'Japan', region: 'Asia', hasCoastline: true, majorPorts: 18 },
  { code: 'KR', name: 'South Korea', region: 'Asia', hasCoastline: true, majorPorts: 8 },
  { code: 'TW', name: 'Taiwan', region: 'Asia', hasCoastline: true, majorPorts: 4 },
  { code: 'SG', name: 'Singapore', region: 'Asia', hasCoastline: true, majorPorts: 1 },
  { code: 'MY', name: 'Malaysia', region: 'Asia', hasCoastline: true, majorPorts: 7 },
  { code: 'TH', name: 'Thailand', region: 'Asia', hasCoastline: true, majorPorts: 5 },
  { code: 'VN', name: 'Vietnam', region: 'Asia', hasCoastline: true, majorPorts: 6 },
  { code: 'ID', name: 'Indonesia', region: 'Asia', hasCoastline: true, majorPorts: 8 },
  { code: 'PH', name: 'Philippines', region: 'Asia', hasCoastline: true, majorPorts: 5 },
  { code: 'HK', name: 'Hong Kong', region: 'Asia', hasCoastline: true, majorPorts: 1 },
  { code: 'IN', name: 'India', region: 'Asia', hasCoastline: true, majorPorts: 13 },
  { code: 'PK', name: 'Pakistan', region: 'Asia', hasCoastline: true, majorPorts: 2 },
  { code: 'BD', name: 'Bangladesh', region: 'Asia', hasCoastline: true, majorPorts: 2 },
  { code: 'LK', name: 'Sri Lanka', region: 'Asia', hasCoastline: true, majorPorts: 2 },
  // Middle East
  { code: 'AE', name: 'United Arab Emirates', region: 'Middle East', hasCoastline: true, majorPorts: 4 },
  { code: 'SA', name: 'Saudi Arabia', region: 'Middle East', hasCoastline: true, majorPorts: 5 },
  { code: 'QA', name: 'Qatar', region: 'Middle East', hasCoastline: true, majorPorts: 1 },
  { code: 'OM', name: 'Oman', region: 'Middle East', hasCoastline: true, majorPorts: 3 },
  { code: 'KW', name: 'Kuwait', region: 'Middle East', hasCoastline: true, majorPorts: 1 },
  { code: 'BH', name: 'Bahrain', region: 'Middle East', hasCoastline: true, majorPorts: 1 },
  { code: 'IQ', name: 'Iraq', region: 'Middle East', hasCoastline: true, majorPorts: 1 },
  { code: 'IR', name: 'Iran', region: 'Middle East', hasCoastline: true, majorPorts: 4 },
  // Europe
  { code: 'NL', name: 'Netherlands', region: 'Europe', hasCoastline: true, majorPorts: 3 },
  { code: 'BE', name: 'Belgium', region: 'Europe', hasCoastline: true, majorPorts: 2 },
  { code: 'DE', name: 'Germany', region: 'Europe', hasCoastline: true, majorPorts: 5 },
  { code: 'GB', name: 'United Kingdom', region: 'Europe', hasCoastline: true, majorPorts: 8 },
  { code: 'FR', name: 'France', region: 'Europe', hasCoastline: true, majorPorts: 7 },
  { code: 'ES', name: 'Spain', region: 'Europe', hasCoastline: true, majorPorts: 6 },
  { code: 'IT', name: 'Italy', region: 'Europe', hasCoastline: true, majorPorts: 8 },
  { code: 'GR', name: 'Greece', region: 'Europe', hasCoastline: true, majorPorts: 4 },
  { code: 'PL', name: 'Poland', region: 'Europe', hasCoastline: true, majorPorts: 3 },
  { code: 'SE', name: 'Sweden', region: 'Europe', hasCoastline: true, majorPorts: 4 },
  { code: 'DK', name: 'Denmark', region: 'Europe', hasCoastline: true, majorPorts: 3 },
  { code: 'FI', name: 'Finland', region: 'Europe', hasCoastline: true, majorPorts: 3 },
  { code: 'NO', name: 'Norway', region: 'Europe', hasCoastline: true, majorPorts: 5 },
  { code: 'PT', name: 'Portugal', region: 'Europe', hasCoastline: true, majorPorts: 3 },
  { code: 'IE', name: 'Ireland', region: 'Europe', hasCoastline: true, majorPorts: 2 },
  { code: 'RU', name: 'Russia', region: 'Europe', hasCoastline: true, majorPorts: 6 },
  { code: 'TR', name: 'Turkey', region: 'Europe', hasCoastline: true, majorPorts: 5 },
  // North America
  { code: 'US', name: 'United States', region: 'North America', hasCoastline: true, majorPorts: 15 },
  { code: 'CA', name: 'Canada', region: 'North America', hasCoastline: true, majorPorts: 5 },
  { code: 'MX', name: 'Mexico', region: 'North America', hasCoastline: true, majorPorts: 4 },
  // South America
  { code: 'BR', name: 'Brazil', region: 'South America', hasCoastline: true, majorPorts: 7 },
  { code: 'AR', name: 'Argentina', region: 'South America', hasCoastline: true, majorPorts: 3 },
  { code: 'CL', name: 'Chile', region: 'South America', hasCoastline: true, majorPorts: 4 },
  { code: 'CO', name: 'Colombia', region: 'South America', hasCoastline: true, majorPorts: 3 },
  { code: 'PE', name: 'Peru', region: 'South America', hasCoastline: true, majorPorts: 2 },
  { code: 'EC', name: 'Ecuador', region: 'South America', hasCoastline: true, majorPorts: 2 },
  // Africa
  { code: 'ZA', name: 'South Africa', region: 'Africa', hasCoastline: true, majorPorts: 4 },
  { code: 'EG', name: 'Egypt', region: 'Africa', hasCoastline: true, majorPorts: 3 },
  { code: 'MA', name: 'Morocco', region: 'Africa', hasCoastline: true, majorPorts: 3 },
  { code: 'NG', name: 'Nigeria', region: 'Africa', hasCoastline: true, majorPorts: 3 },
  { code: 'KE', name: 'Kenya', region: 'Africa', hasCoastline: true, majorPorts: 1 },
  { code: 'TZ', name: 'Tanzania', region: 'Africa', hasCoastline: true, majorPorts: 2 },
  { code: 'GH', name: 'Ghana', region: 'Africa', hasCoastline: true, majorPorts: 2 },
  { code: 'CI', name: 'Ivory Coast', region: 'Africa', hasCoastline: true, majorPorts: 1 },
  { code: 'SN', name: 'Senegal', region: 'Africa', hasCoastline: true, majorPorts: 1 },
  { code: 'DZ', name: 'Algeria', region: 'Africa', hasCoastline: true, majorPorts: 2 },
  // Oceania
  { code: 'AU', name: 'Australia', region: 'Oceania', hasCoastline: true, majorPorts: 8 },
  { code: 'NZ', name: 'New Zealand', region: 'Oceania', hasCoastline: true, majorPorts: 4 },
];

// 100+ Major World Ports with comprehensive data
export const PORTS: Port[] = [
  // === CHINA ===
  {
    unLoCode: 'CNSHA',
    name: 'Shanghai',
    country: 'China',
    countryCode: 'CN',
    region: 'Asia',
    coordinates: { lat: 31.3614, lng: 121.5878 },
    portType: ['Seaport', 'Container Terminal', 'Bulk Terminal'],
    facilities: ['Yangshan Deep Water Port', 'Waigaoqiao', 'Huangpu', 'Luojing'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker', 'RoRo'],
    throughput: '47M+ TEU',
    timezone: 'Asia/Shanghai',
    status: 'active',
  },
  {
    unLoCode: 'CNSZX',
    name: 'Shenzhen',
    country: 'China',
    countryCode: 'CN',
    region: 'Asia',
    coordinates: { lat: 22.4797, lng: 113.9064 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Yantian', 'Shekou', 'Chiwan', 'Mawan'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '28M+ TEU',
    timezone: 'Asia/Shanghai',
    status: 'active',
  },
  {
    unLoCode: 'CNNGB',
    name: 'Ningbo-Zhoushan',
    country: 'China',
    countryCode: 'CN',
    region: 'Asia',
    coordinates: { lat: 29.8683, lng: 121.5440 },
    portType: ['Seaport', 'Container Terminal', 'Bulk Terminal', 'Tanker Terminal'],
    facilities: ['Beilun', 'Chuanshan', 'Meishan', 'Daxie'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker'],
    throughput: '33M+ TEU',
    timezone: 'Asia/Shanghai',
    status: 'active',
  },
  {
    unLoCode: 'CNQIN',
    name: 'Qingdao',
    country: 'China',
    countryCode: 'CN',
    region: 'Asia',
    coordinates: { lat: 36.0671, lng: 120.3826 },
    portType: ['Seaport', 'Container Terminal', 'Bulk Terminal'],
    facilities: ['Qingdao Qianwan', 'Huangdao Oil Port'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker'],
    throughput: '23M+ TEU',
    timezone: 'Asia/Shanghai',
    status: 'active',
  },
  {
    unLoCode: 'CNGZH',
    name: 'Guangzhou',
    country: 'China',
    countryCode: 'CN',
    region: 'Asia',
    coordinates: { lat: 22.9458, lng: 113.5208 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Nansha', 'Huangpu', 'Xinsha'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '24M+ TEU',
    timezone: 'Asia/Shanghai',
    status: 'active',
  },
  {
    unLoCode: 'CNTXG',
    name: 'Tianjin',
    country: 'China',
    countryCode: 'CN',
    region: 'Asia',
    coordinates: { lat: 38.9788, lng: 117.7823 },
    portType: ['Seaport', 'Container Terminal', 'Bulk Terminal'],
    facilities: ['Tianjin Port', 'Xingang'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '20M+ TEU',
    timezone: 'Asia/Shanghai',
    status: 'active',
  },
  {
    unLoCode: 'CNXMN',
    name: 'Xiamen',
    country: 'China',
    countryCode: 'CN',
    region: 'Asia',
    coordinates: { lat: 24.5037, lng: 118.0883 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Haicang', 'Dongdu'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '12M+ TEU',
    timezone: 'Asia/Shanghai',
    status: 'active',
  },
  {
    unLoCode: 'CNDLC',
    name: 'Dalian',
    country: 'China',
    countryCode: 'CN',
    region: 'Asia',
    coordinates: { lat: 38.9141, lng: 121.6368 },
    portType: ['Seaport', 'Container Terminal', 'Bulk Terminal', 'Tanker Terminal'],
    facilities: ['Dayaowan', 'Xianglujiao'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker'],
    throughput: '10M+ TEU',
    timezone: 'Asia/Shanghai',
    status: 'active',
  },
  {
    unLoCode: 'CNYTN',
    name: 'Yantian',
    country: 'China',
    countryCode: 'CN',
    region: 'Asia',
    coordinates: { lat: 22.5633, lng: 114.2742 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Yantian International Container Terminal'],
    vesselTypes: ['Container'],
    throughput: '14M+ TEU',
    timezone: 'Asia/Shanghai',
    status: 'active',
  },
  {
    unLoCode: 'CNLYG',
    name: 'Lianyungang',
    country: 'China',
    countryCode: 'CN',
    region: 'Asia',
    coordinates: { lat: 34.7411, lng: 119.4414 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Lianyungang Port'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '5M+ TEU',
    timezone: 'Asia/Shanghai',
    status: 'active',
  },
  // === SINGAPORE ===
  {
    unLoCode: 'SGSIN',
    name: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    region: 'Asia',
    coordinates: { lat: 1.2644, lng: 103.8198 },
    portType: ['Seaport', 'Container Terminal', 'Tanker Terminal', 'Cruise Terminal'],
    facilities: ['PSA Singapore', 'Jurong Port', 'Tuas'],
    vesselTypes: ['Container', 'Tanker', 'Bulk Carrier', 'RoRo', 'Cruise'],
    throughput: '37M+ TEU',
    timezone: 'Asia/Singapore',
    status: 'active',
  },
  // === SOUTH KOREA ===
  {
    unLoCode: 'KRPUS',
    name: 'Busan',
    country: 'South Korea',
    countryCode: 'KR',
    region: 'Asia',
    coordinates: { lat: 35.1026, lng: 129.0403 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Gamman', 'Sinseondae', 'Shinsamdeung', 'Gamcheon'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '22M+ TEU',
    timezone: 'Asia/Seoul',
    status: 'active',
  },
  {
    unLoCode: 'KRIKH',
    name: 'Incheon',
    country: 'South Korea',
    countryCode: 'KR',
    region: 'Asia',
    coordinates: { lat: 37.4668, lng: 126.6327 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Incheon North Port', 'Incheon South Port'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '3M+ TEU',
    timezone: 'Asia/Seoul',
    status: 'active',
  },
  {
    unLoCode: 'KRYOS',
    name: 'Yeosu',
    country: 'South Korea',
    countryCode: 'KR',
    region: 'Asia',
    coordinates: { lat: 34.7361, lng: 127.7517 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Yeosu Gwangyang Port'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker'],
    throughput: '2M+ TEU',
    timezone: 'Asia/Seoul',
    status: 'active',
  },
  // === HONG KONG ===
  {
    unLoCode: 'HKHKG',
    name: 'Hong Kong',
    country: 'Hong Kong',
    countryCode: 'HK',
    region: 'Asia',
    coordinates: { lat: 22.2855, lng: 114.1577 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Kwai Tsing', 'Victoria Harbour'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '18M+ TEU',
    timezone: 'Asia/Hong_Kong',
    status: 'active',
  },
  // === JAPAN ===
  {
    unLoCode: 'JPYOK',
    name: 'Yokohama',
    country: 'Japan',
    countryCode: 'JP',
    region: 'Asia',
    coordinates: { lat: 35.4603, lng: 139.7644 },
    portType: ['Seaport', 'Container Terminal', 'Bulk Terminal'],
    facilities: ['Honmoku', 'Minami-Honmoku', 'Osanbashi'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '3M+ TEU',
    timezone: 'Asia/Tokyo',
    status: 'active',
  },
  {
    unLoCode: 'JPTYO',
    name: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    region: 'Asia',
    coordinates: { lat: 35.6528, lng: 139.7914 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Oi Container Terminal', 'Aomi', 'Shinagawa'],
    vesselTypes: ['Container', 'RoRo'],
    throughput: '4M+ TEU',
    timezone: 'Asia/Tokyo',
    status: 'active',
  },
  {
    unLoCode: 'JPKOB',
    name: 'Kobe',
    country: 'Japan',
    countryCode: 'JP',
    region: 'Asia',
    coordinates: { lat: 34.6806, lng: 135.1953 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Port Island', 'Rokko Island'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '2M+ TEU',
    timezone: 'Asia/Tokyo',
    status: 'active',
  },
  {
    unLoCode: 'JPOSA',
    name: 'Osaka',
    country: 'Japan',
    countryCode: 'JP',
    region: 'Asia',
    coordinates: { lat: 34.6484, lng: 135.4237 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Sakishima', 'Suminoe'],
    vesselTypes: ['Container', 'RoRo', 'Ferry'],
    throughput: '2M+ TEU',
    timezone: 'Asia/Tokyo',
    status: 'active',
  },
  {
    unLoCode: 'JPNGO',
    name: 'Nagoya',
    country: 'Japan',
    countryCode: 'JP',
    region: 'Asia',
    coordinates: { lat: 35.0988, lng: 136.8822 },
    portType: ['Seaport', 'Container Terminal', 'Bulk Terminal'],
    facilities: ['Tobishima', 'Nakajima'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '3M+ TEU',
    timezone: 'Asia/Tokyo',
    status: 'active',
  },
  // === TAIWAN ===
  {
    unLoCode: 'TWKHH',
    name: 'Kaohsiung',
    country: 'Taiwan',
    countryCode: 'TW',
    region: 'Asia',
    coordinates: { lat: 22.5619, lng: 120.3147 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Terminal 1-6', 'Intercontinental Terminal'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker'],
    throughput: '10M+ TEU',
    timezone: 'Asia/Taipei',
    status: 'active',
  },
  {
    unLoCode: 'TWTPE',
    name: 'Taipei',
    country: 'Taiwan',
    countryCode: 'TW',
    region: 'Asia',
    coordinates: { lat: 25.1613, lng: 121.4234 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Taipei Port'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '3M+ TEU',
    timezone: 'Asia/Taipei',
    status: 'active',
  },
  {
    unLoCode: 'TWTXG',
    name: 'Taichung',
    country: 'Taiwan',
    countryCode: 'TW',
    region: 'Asia',
    coordinates: { lat: 24.2847, lng: 120.5194 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Taichung Port'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '2M+ TEU',
    timezone: 'Asia/Taipei',
    status: 'active',
  },
  // === MALAYSIA ===
  {
    unLoCode: 'MYPKG',
    name: 'Port Klang',
    country: 'Malaysia',
    countryCode: 'MY',
    region: 'Asia',
    coordinates: { lat: 3.0019, lng: 101.3933 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Westports', 'Northport'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker'],
    throughput: '14M+ TEU',
    timezone: 'Asia/Kuala_Lumpur',
    status: 'active',
  },
  {
    unLoCode: 'MYPEN',
    name: 'Penang',
    country: 'Malaysia',
    countryCode: 'MY',
    region: 'Asia',
    coordinates: { lat: 5.4103, lng: 100.3756 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['North Butterworth Container Terminal'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '2M+ TEU',
    timezone: 'Asia/Kuala_Lumpur',
    status: 'active',
  },
  {
    unLoCode: 'MYTPP',
    name: 'Tanjung Pelepas',
    country: 'Malaysia',
    countryCode: 'MY',
    region: 'Asia',
    coordinates: { lat: 1.3586, lng: 103.5367 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['PTP Terminal'],
    vesselTypes: ['Container'],
    throughput: '9M+ TEU',
    timezone: 'Asia/Kuala_Lumpur',
    status: 'active',
  },
  {
    unLoCode: 'MYJHB',
    name: 'Johor',
    country: 'Malaysia',
    countryCode: 'MY',
    region: 'Asia',
    coordinates: { lat: 1.4664, lng: 103.7422 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Pasir Gudang'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker'],
    throughput: '1M+ TEU',
    timezone: 'Asia/Kuala_Lumpur',
    status: 'active',
  },
  // === THAILAND ===
  {
    unLoCode: 'THBKK',
    name: 'Laem Chabang',
    country: 'Thailand',
    countryCode: 'TH',
    region: 'Asia',
    coordinates: { lat: 13.1014, lng: 100.8858 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Terminal A-F'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '8M+ TEU',
    timezone: 'Asia/Bangkok',
    status: 'active',
  },
  {
    unLoCode: 'THSRI',
    name: 'Songkhla',
    country: 'Thailand',
    countryCode: 'TH',
    region: 'Asia',
    coordinates: { lat: 7.1867, lng: 100.5956 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Songkhla Port'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '500K TEU',
    timezone: 'Asia/Bangkok',
    status: 'active',
  },
  // === VIETNAM ===
  {
    unLoCode: 'VNHPH',
    name: 'Haiphong',
    country: 'Vietnam',
    countryCode: 'VN',
    region: 'Asia',
    coordinates: { lat: 20.8519, lng: 106.7042 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Chua Ve', 'Hoang Dieu', 'Tan Cang'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '5M+ TEU',
    timezone: 'Asia/Bangkok',
    status: 'active',
  },
  {
    unLoCode: 'VNSGN',
    name: 'Ho Chi Minh City',
    country: 'Vietnam',
    countryCode: 'VN',
    region: 'Asia',
    coordinates: { lat: 10.7802, lng: 106.7003 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Cat Lai', 'Saigon New Port'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '7M+ TEU',
    timezone: 'Asia/Bangkok',
    status: 'active',
  },
  {
    unLoCode: 'VNDAD',
    name: 'Da Nang',
    country: 'Vietnam',
    countryCode: 'VN',
    region: 'Asia',
    coordinates: { lat: 16.1066, lng: 108.2122 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Tien Sa Port'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '1M+ TEU',
    timezone: 'Asia/Bangkok',
    status: 'active',
  },
  // === INDONESIA ===
  {
    unLoCode: 'IDJKT',
    name: 'Jakarta (Tanjung Priok)',
    country: 'Indonesia',
    countryCode: 'ID',
    region: 'Asia',
    coordinates: { lat: -6.1017, lng: 106.8842 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Tanjung Priok'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker'],
    throughput: '8M+ TEU',
    timezone: 'Asia/Jakarta',
    status: 'active',
  },
  {
    unLoCode: 'IDSUB',
    name: 'Surabaya',
    country: 'Indonesia',
    countryCode: 'ID',
    region: 'Asia',
    coordinates: { lat: -7.2029, lng: 112.7317 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Tanjung Perak'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '4M+ TEU',
    timezone: 'Asia/Jakarta',
    status: 'active',
  },
  // === PHILIPPINES ===
  {
    unLoCode: 'PHMNL',
    name: 'Manila',
    country: 'Philippines',
    countryCode: 'PH',
    region: 'Asia',
    coordinates: { lat: 14.5944, lng: 120.9704 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Manila International Container Terminal', 'Manila South Harbor'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '5M+ TEU',
    timezone: 'Asia/Manila',
    status: 'active',
  },
  // === INDIA ===
  {
    unLoCode: 'INNSA',
    name: 'Nhava Sheva (Jawaharlal Nehru)',
    country: 'India',
    countryCode: 'IN',
    region: 'Asia',
    coordinates: { lat: 18.9639, lng: 72.9492 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['JNPT'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '6M+ TEU',
    timezone: 'Asia/Kolkata',
    status: 'active',
  },
  {
    unLoCode: 'INBOM',
    name: 'Mumbai',
    country: 'India',
    countryCode: 'IN',
    region: 'Asia',
    coordinates: { lat: 18.9750, lng: 72.8258 },
    portType: ['Seaport', 'Container Terminal', 'Bulk Terminal'],
    facilities: ['Mumbai Port Trust'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker'],
    throughput: '1M+ TEU',
    timezone: 'Asia/Kolkata',
    status: 'active',
  },
  {
    unLoCode: 'INMAA',
    name: 'Chennai',
    country: 'India',
    countryCode: 'IN',
    region: 'Asia',
    coordinates: { lat: 13.1239, lng: 80.3003 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Chennai Port'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '2M+ TEU',
    timezone: 'Asia/Kolkata',
    status: 'active',
  },
  {
    unLoCode: 'INMUN',
    name: 'Mundra',
    country: 'India',
    countryCode: 'IN',
    region: 'Asia',
    coordinates: { lat: 22.8203, lng: 69.8417 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Mundra Port'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker'],
    throughput: '5M+ TEU',
    timezone: 'Asia/Kolkata',
    status: 'active',
  },
  {
    unLoCode: 'INCOK',
    name: 'Kochi',
    country: 'India',
    countryCode: 'IN',
    region: 'Asia',
    coordinates: { lat: 9.9667, lng: 76.2500 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Vallarpadam Terminal'],
    vesselTypes: ['Container', 'Tanker'],
    throughput: '1M+ TEU',
    timezone: 'Asia/Kolkata',
    status: 'active',
  },
  // === SRI LANKA ===
  {
    unLoCode: 'LKCMB',
    name: 'Colombo',
    country: 'Sri Lanka',
    countryCode: 'LK',
    region: 'Asia',
    coordinates: { lat: 6.9471, lng: 79.8458 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Jaya Container Terminal', 'Colombo International Container Terminal'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker'],
    throughput: '7M+ TEU',
    timezone: 'Asia/Colombo',
    status: 'active',
  },
  // === BANGLADESH ===
  {
    unLoCode: 'BDCGP',
    name: 'Chittagong',
    country: 'Bangladesh',
    countryCode: 'BD',
    region: 'Asia',
    coordinates: { lat: 22.3071, lng: 91.7769 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Chittagong Port'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '3M+ TEU',
    timezone: 'Asia/Dhaka',
    status: 'active',
  },
  // === UAE ===
  {
    unLoCode: 'AEJEA',
    name: 'Jebel Ali (Dubai)',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    region: 'Middle East',
    coordinates: { lat: 25.0072, lng: 55.0266 },
    portType: ['Seaport', 'Container Terminal', 'Bulk Terminal'],
    facilities: ['Terminal 1', 'Terminal 2', 'Terminal 3', 'Terminal 4'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo', 'Tanker'],
    throughput: '15M+ TEU',
    timezone: 'Asia/Dubai',
    status: 'active',
  },
  {
    unLoCode: 'AEAUH',
    name: 'Abu Dhabi',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    region: 'Middle East',
    coordinates: { lat: 24.4539, lng: 54.3773 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Khalifa Port'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '3M+ TEU',
    timezone: 'Asia/Dubai',
    status: 'active',
  },
  // === SAUDI ARABIA ===
  {
    unLoCode: 'SADAM',
    name: 'Dammam',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    region: 'Middle East',
    coordinates: { lat: 26.5500, lng: 50.2000 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['King Abdul Aziz Port'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker'],
    throughput: '2M+ TEU',
    timezone: 'Asia/Riyadh',
    status: 'active',
  },
  {
    unLoCode: 'SAJED',
    name: 'Jeddah',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    region: 'Middle East',
    coordinates: { lat: 21.4814, lng: 39.1822 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Jeddah Islamic Port'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker', 'RoRo'],
    throughput: '4M+ TEU',
    timezone: 'Asia/Riyadh',
    status: 'active',
  },
  // === QATAR ===
  {
    unLoCode: 'QAHMD',
    name: 'Hamad Port',
    country: 'Qatar',
    countryCode: 'QA',
    region: 'Middle East',
    coordinates: { lat: 25.0500, lng: 51.6500 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Hamad Port'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '6M+ TEU',
    timezone: 'Asia/Qatar',
    status: 'active',
  },
  // === OMAN ===
  {
    unLoCode: 'OMSLL',
    name: 'Salalah',
    country: 'Oman',
    countryCode: 'OM',
    region: 'Middle East',
    coordinates: { lat: 16.9361, lng: 53.9889 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Salalah Port'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '4M+ TEU',
    timezone: 'Asia/Muscat',
    status: 'active',
  },
  // === NETHERLANDS ===
  {
    unLoCode: 'NLRTM',
    name: 'Rotterdam',
    country: 'Netherlands',
    countryCode: 'NL',
    region: 'Europe',
    coordinates: { lat: 51.9054, lng: 4.4454 },
    portType: ['Seaport', 'Container Terminal', 'Bulk Terminal', 'Tanker Terminal', 'RoRo Terminal'],
    facilities: ['Maasvlakte', 'Europoort', 'Waalhaven', 'Botlek'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker', 'RoRo'],
    throughput: '15M+ TEU',
    timezone: 'Europe/Amsterdam',
    status: 'active',
  },
  {
    unLoCode: 'NLAMS',
    name: 'Amsterdam',
    country: 'Netherlands',
    countryCode: 'NL',
    region: 'Europe',
    coordinates: { lat: 52.4000, lng: 4.9167 },
    portType: ['Seaport', 'Bulk Terminal', 'Tanker Terminal'],
    facilities: ['Port of Amsterdam'],
    vesselTypes: ['Bulk Carrier', 'Tanker'],
    throughput: '1M+ TEU',
    timezone: 'Europe/Amsterdam',
    status: 'active',
  },
  // === BELGIUM ===
  {
    unLoCode: 'BEANR',
    name: 'Antwerp',
    country: 'Belgium',
    countryCode: 'BE',
    region: 'Europe',
    coordinates: { lat: 51.2640, lng: 4.3983 },
    portType: ['Seaport', 'Container Terminal', 'Bulk Terminal', 'Tanker Terminal'],
    facilities: ['Deurganckdok', 'Europaterminal', 'Noordsea Terminal'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker', 'RoRo'],
    throughput: '12M+ TEU',
    timezone: 'Europe/Brussels',
    status: 'active',
  },
  {
    unLoCode: 'BEBRU',
    name: 'Zeebrugge',
    country: 'Belgium',
    countryCode: 'BE',
    region: 'Europe',
    coordinates: { lat: 51.3283, lng: 3.2022 },
    portType: ['Seaport', 'Container Terminal', 'RoRo Terminal'],
    facilities: ['Zeebrugge Port'],
    vesselTypes: ['Container', 'RoRo', 'Bulk Carrier'],
    throughput: '3M+ TEU',
    timezone: 'Europe/Brussels',
    status: 'active',
  },
  // === GERMANY ===
  {
    unLoCode: 'DEHAM',
    name: 'Hamburg',
    country: 'Germany',
    countryCode: 'DE',
    region: 'Europe',
    coordinates: { lat: 53.5397, lng: 9.9918 },
    portType: ['Seaport', 'Container Terminal', 'Bulk Terminal'],
    facilities: ['Altenwerder', 'Eurogate', 'Tollerort', 'Burchardkai'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '9M+ TEU',
    timezone: 'Europe/Berlin',
    status: 'active',
  },
  {
    unLoCode: 'DEBRV',
    name: 'Bremerhaven',
    country: 'Germany',
    countryCode: 'DE',
    region: 'Europe',
    coordinates: { lat: 53.5667, lng: 8.5667 },
    portType: ['Seaport', 'Container Terminal', 'RoRo Terminal'],
    facilities: ['NTB', 'MSC Gate'],
    vesselTypes: ['Container', 'RoRo'],
    throughput: '5M+ TEU',
    timezone: 'Europe/Berlin',
    status: 'active',
  },
  {
    unLoCode: 'DEWES',
    name: 'Wilhelmshaven',
    country: 'Germany',
    countryCode: 'DE',
    region: 'Europe',
    coordinates: { lat: 53.5167, lng: 8.1500 },
    portType: ['Seaport', 'Container Terminal', 'Tanker Terminal'],
    facilities: ['JadeWeserPort'],
    vesselTypes: ['Container', 'Tanker'],
    throughput: '1M+ TEU',
    timezone: 'Europe/Berlin',
    status: 'active',
  },
  // === UNITED KINGDOM ===
  {
    unLoCode: 'GBFXT',
    name: 'Felixstowe',
    country: 'United Kingdom',
    countryCode: 'GB',
    region: 'Europe',
    coordinates: { lat: 51.9537, lng: 1.3511 },
    portType: ['Seaport', 'Container Terminal', 'RoRo Terminal'],
    facilities: ['Trinity Terminal', 'Berths 1-9'],
    vesselTypes: ['Container', 'RoRo'],
    throughput: '4M+ TEU',
    timezone: 'Europe/London',
    status: 'active',
  },
  {
    unLoCode: 'GBSOU',
    name: 'Southampton',
    country: 'United Kingdom',
    countryCode: 'GB',
    region: 'Europe',
    coordinates: { lat: 50.9000, lng: -1.4167 },
    portType: ['Seaport', 'Container Terminal', 'RoRo Terminal', 'Cruise Terminal'],
    facilities: ['DP World Southampton', 'ABP Southampton'],
    vesselTypes: ['Container', 'RoRo', 'Cruise'],
    throughput: '2M+ TEU',
    timezone: 'Europe/London',
    status: 'active',
  },
  {
    unLoCode: 'GBLGP',
    name: 'Liverpool',
    country: 'United Kingdom',
    countryCode: 'GB',
    region: 'Europe',
    coordinates: { lat: 53.4500, lng: -3.0000 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Liverpool2', 'Royal Seaforth'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '1M+ TEU',
    timezone: 'Europe/London',
    status: 'active',
  },
  {
    unLoCode: 'GBLDH',
    name: 'London Gateway',
    country: 'United Kingdom',
    countryCode: 'GB',
    region: 'Europe',
    coordinates: { lat: 51.5167, lng: 0.6000 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['London Gateway'],
    vesselTypes: ['Container'],
    throughput: '2M+ TEU',
    timezone: 'Europe/London',
    status: 'active',
  },
  // === FRANCE ===
  {
    unLoCode: 'FRMRS',
    name: 'Marseille',
    country: 'France',
    countryCode: 'FR',
    region: 'Europe',
    coordinates: { lat: 43.2964, lng: 5.3700 },
    portType: ['Seaport', 'Container Terminal', 'Tanker Terminal'],
    facilities: ['Fos-sur-Mer', 'Grand Port Maritime de Marseille'],
    vesselTypes: ['Container', 'Tanker', 'Bulk Carrier'],
    throughput: '2M+ TEU',
    timezone: 'Europe/Paris',
    status: 'active',
  },
  {
    unLoCode: 'FRLEH',
    name: 'Le Havre',
    country: 'France',
    countryCode: 'FR',
    region: 'Europe',
    coordinates: { lat: 49.4833, lng: 0.1167 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Port 2000'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '3M+ TEU',
    timezone: 'Europe/Paris',
    status: 'active',
  },
  // === SPAIN ===
  {
    unLoCode: 'ESALG',
    name: 'Algeciras',
    country: 'Spain',
    countryCode: 'ES',
    region: 'Europe',
    coordinates: { lat: 36.1333, lng: -5.4500 },
    portType: ['Seaport', 'Container Terminal', 'Tanker Terminal'],
    facilities: ['APM Terminals Algeciras', 'TTI Algeciras'],
    vesselTypes: ['Container', 'Tanker', 'Bulk Carrier', 'RoRo'],
    throughput: '5M+ TEU',
    timezone: 'Europe/Madrid',
    status: 'active',
  },
  {
    unLoCode: 'ESBAR',
    name: 'Barcelona',
    country: 'Spain',
    countryCode: 'ES',
    region: 'Europe',
    coordinates: { lat: 41.3500, lng: 2.1500 },
    portType: ['Seaport', 'Container Terminal', 'RoRo Terminal', 'Cruise Terminal'],
    facilities: ['APM Terminals Barcelona', 'BEST'],
    vesselTypes: ['Container', 'RoRo', 'Cruise'],
    throughput: '3M+ TEU',
    timezone: 'Europe/Madrid',
    status: 'active',
  },
  {
    unLoCode: 'ESVLC',
    name: 'Valencia',
    country: 'Spain',
    countryCode: 'ES',
    region: 'Europe',
    coordinates: { lat: 39.4500, lng: -0.3333 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Valencia Container Terminal', 'TCV'],
    vesselTypes: ['Container', 'RoRo', 'Bulk Carrier'],
    throughput: '5M+ TEU',
    timezone: 'Europe/Madrid',
    status: 'active',
  },
  // === ITALY ===
  {
    unLoCode: 'ITGOA',
    name: 'Genoa',
    country: 'Italy',
    countryCode: 'IT',
    region: 'Europe',
    coordinates: { lat: 44.4000, lng: 8.9167 },
    portType: ['Seaport', 'Container Terminal', 'RoRo Terminal'],
    facilities: ['VTE', 'SECH'],
    vesselTypes: ['Container', 'RoRo', 'Bulk Carrier'],
    throughput: '2M+ TEU',
    timezone: 'Europe/Rome',
    status: 'active',
  },
  {
    unLoCode: 'ITGVA',
    name: 'Gioia Tauro',
    country: 'Italy',
    countryCode: 'IT',
    region: 'Europe',
    coordinates: { lat: 38.4333, lng: 15.9000 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Medcenter Container Terminal'],
    vesselTypes: ['Container'],
    throughput: '3M+ TEU',
    timezone: 'Europe/Rome',
    status: 'active',
  },
  // === GREECE ===
  {
    unLoCode: 'GRPIR',
    name: 'Piraeus',
    country: 'Greece',
    countryCode: 'GR',
    region: 'Europe',
    coordinates: { lat: 37.9500, lng: 23.6500 },
    portType: ['Seaport', 'Container Terminal', 'RoRo Terminal', 'Cruise Terminal'],
    facilities: ['Piraeus Container Terminal', 'COSCO Piraeus'],
    vesselTypes: ['Container', 'RoRo', 'Cruise', 'Ferry'],
    throughput: '5M+ TEU',
    timezone: 'Europe/Athens',
    status: 'active',
  },
  // === TURKEY ===
  {
    unLoCode: 'TRIST',
    name: 'Istanbul',
    country: 'Turkey',
    countryCode: 'TR',
    region: 'Europe',
    coordinates: { lat: 41.0000, lng: 29.0000 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Ambarli', 'Kumport', 'Marport'],
    vesselTypes: ['Container', 'RoRo', 'Bulk Carrier'],
    throughput: '3M+ TEU',
    timezone: 'Europe/Istanbul',
    status: 'active',
  },
  // === USA ===
  {
    unLoCode: 'USLAX',
    name: 'Los Angeles',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    coordinates: { lat: 33.7405, lng: -118.2716 },
    portType: ['Seaport', 'Container Terminal', 'RoRo Terminal'],
    facilities: ['APM Terminals', 'TraPac', 'YTI', 'Everport'],
    vesselTypes: ['Container', 'RoRo', 'Bulk Carrier'],
    throughput: '10M+ TEU',
    timezone: 'America/Los_Angeles',
    status: 'active',
  },
  {
    unLoCode: 'USLGB',
    name: 'Long Beach',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    coordinates: { lat: 33.7541, lng: -118.2171 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['TTI', 'PCT', 'ITS', 'SSA Marine'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '9M+ TEU',
    timezone: 'America/Los_Angeles',
    status: 'active',
  },
  {
    unLoCode: 'USNYC',
    name: 'New York/New Jersey',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    coordinates: { lat: 40.6659, lng: -74.0450 },
    portType: ['Seaport', 'Container Terminal', 'RoRo Terminal'],
    facilities: ['APM Terminal', 'GCT Bayonne', 'GCT New York', 'PNCT'],
    vesselTypes: ['Container', 'RoRo', 'Bulk Carrier'],
    throughput: '8M+ TEU',
    timezone: 'America/New_York',
    status: 'active',
  },
  {
    unLoCode: 'USSAV',
    name: 'Savannah',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    coordinates: { lat: 32.0809, lng: -81.0875 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Garden City Terminal'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '5M+ TEU',
    timezone: 'America/New_York',
    status: 'active',
  },
  {
    unLoCode: 'USOAK',
    name: 'Oakland',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    coordinates: { lat: 37.8000, lng: -122.3000 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Oakland International Container Terminal'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '2M+ TEU',
    timezone: 'America/Los_Angeles',
    status: 'active',
  },
  {
    unLoCode: 'USSEA',
    name: 'Seattle',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    coordinates: { lat: 47.2667, lng: -122.3833 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Terminal 5', 'Terminal 18', 'Terminal 30', 'Terminal 46'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '3M+ TEU',
    timezone: 'America/Los_Angeles',
    status: 'active',
  },
  {
    unLoCode: 'USTIW',
    name: 'Tacoma',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    coordinates: { lat: 47.2667, lng: -122.4500 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Washington United Terminals', 'Husky Terminal'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '2M+ TEU',
    timezone: 'America/Los_Angeles',
    status: 'active',
  },
  {
    unLoCode: 'USHOU',
    name: 'Houston',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    coordinates: { lat: 29.7500, lng: -95.1000 },
    portType: ['Seaport', 'Container Terminal', 'Tanker Terminal', 'Bulk Terminal'],
    facilities: ['Barbours Cut', 'Bayport'],
    vesselTypes: ['Container', 'Tanker', 'Bulk Carrier'],
    throughput: '3M+ TEU',
    timezone: 'America/Chicago',
    status: 'active',
  },
  {
    unLoCode: 'USCHS',
    name: 'Charleston',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    coordinates: { lat: 32.7833, lng: -79.9333 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Wando Welch Terminal', 'Columbus Street Terminal'],
    vesselTypes: ['Container', 'RoRo'],
    throughput: '2M+ TEU',
    timezone: 'America/New_York',
    status: 'active',
  },
  {
    unLoCode: 'USMIA',
    name: 'Miami',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    coordinates: { lat: 25.7667, lng: -80.1667 },
    portType: ['Seaport', 'Container Terminal', 'RoRo Terminal', 'Cruise Terminal'],
    facilities: ['PortMiami'],
    vesselTypes: ['Container', 'RoRo', 'Cruise'],
    throughput: '1M+ TEU',
    timezone: 'America/New_York',
    status: 'active',
  },
  // === CANADA ===
  {
    unLoCode: 'CAVAN',
    name: 'Vancouver',
    country: 'Canada',
    countryCode: 'CA',
    region: 'North America',
    coordinates: { lat: 49.2833, lng: -123.1333 },
    portType: ['Seaport', 'Container Terminal', 'Bulk Terminal'],
    facilities: ['Centerm', 'Vanterm', 'Deltaport'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker'],
    throughput: '3M+ TEU',
    timezone: 'America/Vancouver',
    status: 'active',
  },
  {
    unLoCode: 'CAMTR',
    name: 'Montreal',
    country: 'Canada',
    countryCode: 'CA',
    region: 'North America',
    coordinates: { lat: 45.5000, lng: -73.5500 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Termont', 'Viau Terminal'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '2M+ TEU',
    timezone: 'America/Montreal',
    status: 'active',
  },
  // === MEXICO ===
  {
    unLoCode: 'MXLZC',
    name: 'Lazaro Cardenas',
    country: 'Mexico',
    countryCode: 'MX',
    region: 'North America',
    coordinates: { lat: 17.9500, lng: -102.1833 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['APM Terminals Lazaro Cardenas'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '2M+ TEU',
    timezone: 'America/Mexico_City',
    status: 'active',
  },
  {
    unLoCode: 'MXMEX',
    name: 'Manzanillo',
    country: 'Mexico',
    countryCode: 'MX',
    region: 'North America',
    coordinates: { lat: 19.0500, lng: -104.3333 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['SSA Manzanillo', 'Tmsa'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '3M+ TEU',
    timezone: 'America/Mexico_City',
    status: 'active',
  },
  // === BRAZIL ===
  {
    unLoCode: 'BRSSZ',
    name: 'Santos',
    country: 'Brazil',
    countryCode: 'BR',
    region: 'South America',
    coordinates: { lat: -23.9618, lng: -46.2978 },
    portType: ['Seaport', 'Container Terminal', 'Bulk Terminal', 'Tanker Terminal'],
    facilities: ['Tecon', 'Libra', 'BTP'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker', 'RoRo'],
    throughput: '4M+ TEU',
    timezone: 'America/Sao_Paulo',
    status: 'active',
  },
  {
    unLoCode: 'BRRIO',
    name: 'Rio de Janeiro',
    country: 'Brazil',
    countryCode: 'BR',
    region: 'South America',
    coordinates: { lat: -22.9000, lng: -43.2333 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Rio Grande Terminal'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker'],
    throughput: '1M+ TEU',
    timezone: 'America/Sao_Paulo',
    status: 'active',
  },
  {
    unLoCode: 'BRPOA',
    name: 'Porto Alegre',
    country: 'Brazil',
    countryCode: 'BR',
    region: 'South America',
    coordinates: { lat: -30.0333, lng: -51.2333 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Rio Grande Port'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '1M+ TEU',
    timezone: 'America/Sao_Paulo',
    status: 'active',
  },
  // === ARGENTINA ===
  {
    unLoCode: 'ARBUE',
    name: 'Buenos Aires',
    country: 'Argentina',
    countryCode: 'AR',
    region: 'South America',
    coordinates: { lat: -34.6000, lng: -58.3667 },
    portType: ['Seaport', 'Container Terminal', 'RoRo Terminal'],
    facilities: ['Terminal 1-4', 'Exolgan'],
    vesselTypes: ['Container', 'RoRo', 'Bulk Carrier'],
    throughput: '1M+ TEU',
    timezone: 'America/Buenos_Aires',
    status: 'active',
  },
  // === CHILE ===
  {
    unLoCode: 'CLSAI',
    name: 'San Antonio',
    country: 'Chile',
    countryCode: 'CL',
    region: 'South America',
    coordinates: { lat: -33.6000, lng: -71.6333 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Puerto San Antonio'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '1M+ TEU',
    timezone: 'America/Santiago',
    status: 'active',
  },
  {
    unLoCode: 'CLVAL',
    name: 'Valparaiso',
    country: 'Chile',
    countryCode: 'CL',
    region: 'South America',
    coordinates: { lat: -33.0333, lng: -71.6167 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Terminal Pacifico Sur'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '1M+ TEU',
    timezone: 'America/Santiago',
    status: 'active',
  },
  // === COLOMBIA ===
  {
    unLoCode: 'COCTG',
    name: 'Cartagena',
    country: 'Colombia',
    countryCode: 'CO',
    region: 'South America',
    coordinates: { lat: 10.4167, lng: -75.5333 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Contecar', 'SPRC'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker'],
    throughput: '2M+ TEU',
    timezone: 'America/Bogota',
    status: 'active',
  },
  // === PERU ===
  {
    unLoCode: 'PECAL',
    name: 'Callao',
    country: 'Peru',
    countryCode: 'PE',
    region: 'South America',
    coordinates: { lat: -12.0500, lng: -77.1500 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['APM Terminals Callao', 'DP World Callao'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '2M+ TEU',
    timezone: 'America/Lima',
    status: 'active',
  },
  // === SOUTH AFRICA ===
  {
    unLoCode: 'ZADUR',
    name: 'Durban',
    country: 'South Africa',
    countryCode: 'ZA',
    region: 'Africa',
    coordinates: { lat: -29.8740, lng: 31.0245 },
    portType: ['Seaport', 'Container Terminal', 'Bulk Terminal', 'RoRo Terminal'],
    facilities: ['Pier 1', 'Pier 2', 'Maydon Wharf'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker', 'RoRo'],
    throughput: '3M+ TEU',
    timezone: 'Africa/Johannesburg',
    status: 'active',
  },
  {
    unLoCode: 'ZACPT',
    name: 'Cape Town',
    country: 'South Africa',
    countryCode: 'ZA',
    region: 'Africa',
    coordinates: { lat: -33.9000, lng: 18.4333 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Cape Town Container Terminal'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '1M+ TEU',
    timezone: 'Africa/Johannesburg',
    status: 'active',
  },
  // === EGYPT ===
  {
    unLoCode: 'EGPSD',
    name: 'Port Said',
    country: 'Egypt',
    countryCode: 'EG',
    region: 'Africa',
    coordinates: { lat: 31.2667, lng: 32.3000 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['SCCT', 'Port Said Port'],
    vesselTypes: ['Container', 'Bulk Carrier'],
    throughput: '4M+ TEU',
    timezone: 'Africa/Cairo',
    status: 'active',
  },
  {
    unLoCode: 'EGSUZ',
    name: 'Suez',
    country: 'Egypt',
    countryCode: 'EG',
    region: 'Africa',
    coordinates: { lat: 29.9667, lng: 32.5500 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Suez Port'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker'],
    throughput: '1M+ TEU',
    timezone: 'Africa/Cairo',
    status: 'active',
  },
  // === MOROCCO ===
  {
    unLoCode: 'MATNG',
    name: 'Tanger Med',
    country: 'Morocco',
    countryCode: 'MA',
    region: 'Africa',
    coordinates: { lat: 35.8696, lng: -5.7998 },
    portType: ['Seaport', 'Container Terminal', 'RoRo Terminal'],
    facilities: ['TC1', 'TC2', 'TC3'],
    vesselTypes: ['Container', 'RoRo', 'Bulk Carrier'],
    throughput: '7M+ TEU',
    timezone: 'Africa/Casablanca',
    status: 'active',
  },
  {
    unLoCode: 'MACAS',
    name: 'Casablanca',
    country: 'Morocco',
    countryCode: 'MA',
    region: 'Africa',
    coordinates: { lat: 33.6000, lng: -7.6167 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Casablanca Port'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '1M+ TEU',
    timezone: 'Africa/Casablanca',
    status: 'active',
  },
  // === NIGERIA ===
  {
    unLoCode: 'NGLOS',
    name: 'Lagos (Apapa)',
    country: 'Nigeria',
    countryCode: 'NG',
    region: 'Africa',
    coordinates: { lat: 6.4500, lng: 3.4000 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['AP Moller Terminal', 'Tincan Island'],
    vesselTypes: ['Container', 'Bulk Carrier', 'Tanker'],
    throughput: '2M+ TEU',
    timezone: 'Africa/Lagos',
    status: 'active',
  },
  // === KENYA ===
  {
    unLoCode: 'KEMBA',
    name: 'Mombasa',
    country: 'Kenya',
    countryCode: 'KE',
    region: 'Africa',
    coordinates: { lat: -4.0333, lng: 39.6667 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Mombasa Container Terminal'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '1M+ TEU',
    timezone: 'Africa/Nairobi',
    status: 'active',
  },
  // === AUSTRALIA ===
  {
    unLoCode: 'AUSYD',
    name: 'Sydney',
    country: 'Australia',
    countryCode: 'AU',
    region: 'Oceania',
    coordinates: { lat: -33.8567, lng: 151.1996 },
    portType: ['Seaport', 'Container Terminal', 'RoRo Terminal', 'Cruise Terminal'],
    facilities: ['Port Botany'],
    vesselTypes: ['Container', 'RoRo', 'Cruise', 'Bulk Carrier'],
    throughput: '2M+ TEU',
    timezone: 'Australia/Sydney',
    status: 'active',
  },
  {
    unLoCode: 'AUMEL',
    name: 'Melbourne',
    country: 'Australia',
    countryCode: 'AU',
    region: 'Oceania',
    coordinates: { lat: -37.8500, lng: 144.9333 },
    portType: ['Seaport', 'Container Terminal', 'RoRo Terminal'],
    facilities: ['Webb Dock', 'Swanson Dock'],
    vesselTypes: ['Container', 'RoRo', 'Bulk Carrier'],
    throughput: '3M+ TEU',
    timezone: 'Australia/Melbourne',
    status: 'active',
  },
  {
    unLoCode: 'AUBNE',
    name: 'Brisbane',
    country: 'Australia',
    countryCode: 'AU',
    region: 'Oceania',
    coordinates: { lat: -27.3833, lng: 153.1500 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Brisbane Container Terminal'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '1M+ TEU',
    timezone: 'Australia/Brisbane',
    status: 'active',
  },
  {
    unLoCode: 'AUFRE',
    name: 'Fremantle',
    country: 'Australia',
    countryCode: 'AU',
    region: 'Oceania',
    coordinates: { lat: -32.0500, lng: 115.7333 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Fremantle Port'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '1M+ TEU',
    timezone: 'Australia/Perth',
    status: 'active',
  },
  // === NEW ZEALAND ===
  {
    unLoCode: 'NZAKL',
    name: 'Auckland',
    country: 'New Zealand',
    countryCode: 'NZ',
    region: 'Oceania',
    coordinates: { lat: -36.8500, lng: 174.7833 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Fergusson Container Terminal'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '1M+ TEU',
    timezone: 'Pacific/Auckland',
    status: 'active',
  },
  {
    unLoCode: 'NZWLG',
    name: 'Wellington',
    country: 'New Zealand',
    countryCode: 'NZ',
    region: 'Oceania',
    coordinates: { lat: -41.2833, lng: 174.7833 },
    portType: ['Seaport', 'Container Terminal', 'Ferry Terminal'],
    facilities: ['Wellington Port'],
    vesselTypes: ['Container', 'RoRo', 'Ferry'],
    throughput: '500K TEU',
    timezone: 'Pacific/Auckland',
    status: 'active',
  },
  {
    unLoCode: 'NZCHC',
    name: 'Lyttelton (Christchurch)',
    country: 'New Zealand',
    countryCode: 'NZ',
    region: 'Oceania',
    coordinates: { lat: -43.6000, lng: 172.7167 },
    portType: ['Seaport', 'Container Terminal'],
    facilities: ['Lyttelton Port'],
    vesselTypes: ['Container', 'Bulk Carrier', 'RoRo'],
    throughput: '500K TEU',
    timezone: 'Pacific/Auckland',
    status: 'active',
  },
];

// Helper functions
export function getPortByUnLoCode(code: string): Port | undefined {
  return PORTS.find(p => p.unLoCode.toLowerCase() === code.toLowerCase());
}

export function searchPorts(query: string): Port[] {
  const q = query.toLowerCase();
  return PORTS.filter(p => 
    p.name.toLowerCase().includes(q) ||
    p.unLoCode.toLowerCase().includes(q) ||
    p.country.toLowerCase().includes(q) ||
    p.countryCode.toLowerCase().includes(q)
  );
}

export function getPortsByCountry(countryCode: string): Port[] {
  return PORTS.filter(p => p.countryCode.toLowerCase() === countryCode.toLowerCase());
}

export function getPortsByRegion(region: string): Port[] {
  return PORTS.filter(p => p.region.toLowerCase() === region.toLowerCase());
}

export function getMajorPorts(limit: number = 20): Port[] {
  return PORTS
    .filter(p => p.throughput && p.throughput.includes('M+ TEU'))
    .slice(0, limit);
}

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find(c => c.code.toLowerCase() === code.toLowerCase());
}

// UN/LOCODE structure explanation
export const UNLOCODE_INFO = {
  structure: {
    firstTwoChars: 'ISO 3166-1 alpha-2 country code',
    lastThreeChars: 'Location code within the country (letters or numbers)',
    example: 'CNSHA = CN (China) + SHA (Shanghai)',
  },
  types: {
    '1': 'Sea port or freight terminal',
    '2': 'Rail terminal',
    '3': 'Road terminal',
    '4': 'Airport',
    '5': 'Postal exchange office',
    '6': 'Inland clearance depot (ICD)',
    '7': 'Fixed transport functions (e.g., oil platform)',
    '8': 'Not used',
    '9': 'Not used',
    'B': 'Border crossing function',
    '0': 'Code no longer in use',
  },
  functions: {
    '1': 'Maritime transport (sea port)',
    '2': 'Rail transport',
    '3': 'Road transport',
    '4': 'Air transport',
    '5': 'Mail (post office)',
    '6': 'Inland water transport',
    '7': 'Fixed transport',
    'A': 'Cargo handling (all)',
    'B': 'Cargo handling (bulk)',
    'C': 'Cargo handling (container)',
    'D': 'Cargo handling (general)',
    'F': 'Ferry operations',
    'R': 'RoRo cargo handling',
  },
};
