import { Metadata } from "next";
import Link from "next/link";
import {
  Link as LinkIcon,
  BookOpen,
  Lightbulb,
  AlertTriangle,
  HelpCircle,
  ArrowRight,
  CheckCircle2,
  Info,
  Weight,
  Ship,
  Zap,
} from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { LashingForceCalculator } from "@/components/tools/LashingForceCalculator";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

export const metadata: Metadata = {
  title: "Lashing Force Calculator | Shiportrade.com",
  description: "Calculate required lashing forces for project cargo and heavy lift shipments. Compliant with IMO CSS Code standards.",
  keywords: ["lashing force calculator", "cargo securing", "project cargo lashing", "heavy lift calculation", "CSS Code"],
  openGraph: {
    title: "Lashing Force Calculator - Project Cargo",
    description: "Calculate lashing requirements for project cargo and heavy lift shipments.",
    type: "website",
  },
};

export default function LashingForcePage() {
  return (
    <div className="container mx-auto px-4 py-8">
      {/* Breadcrumb */}
      <nav className="flex items-center gap-2 text-sm text-muted-foreground mb-6">
        <Link href="/tools" className="hover:text-foreground">Tools</Link>
        <span>/</span>
        <Link href="/tools/project-cargo" className="hover:text-foreground">Project Cargo</Link>
        <span>/</span>
        <span className="text-foreground">Lashing Force Calculator</span>
      </nav>

      {/* Hero Section */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-12 h-12 rounded-xl bg-[var(--ocean)]/10 flex items-center justify-center">
            <LinkIcon className="h-6 w-6 text-[var(--ocean)]" />
          </div>
          <div>
            <h1 className="text-3xl font-bold">Lashing Force Calculator</h1>
            <p className="text-muted-foreground">Calculate cargo securing requirements</p>
          </div>
        </div>
        <Badge className="gradient-ocean text-white">Free Tool</Badge>
      </div>

      {/* Calculator */}
      <LashingForceCalculator />

      <Separator className="my-12" />

      {/* Educational Section */}
      <div className="grid lg:grid-cols-3 gap-8">
        {/* What is Lashing */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-lg">
              <BookOpen className="h-5 w-5 text-[var(--ocean)]" />
              What is Lashing?
            </CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert">
            <p className="text-muted-foreground">
              <strong>Lashing</strong> is the process of securing cargo to prevent movement during 
              transportation by sea, road, or rail. It involves using various securing equipment 
              like wire ropes, chains, webbing straps, and turnbuckles to restrain cargo against 
              forces generated by vehicle or vessel motions.
            </p>
            <p className="text-muted-foreground mt-3">
              For project cargo and heavy lift shipments, proper lashing is critical for safety 
              and regulatory compliance. Incorrect lashing can lead to cargo damage, vessel 
              instability, and serious accidents.
            </p>
          </CardContent>
        </Card>

        {/* Forces */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-lg">
              <Zap className="h-5 w-5 text-[var(--ocean)]" />
              Forces on Cargo
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-3">
              <div className="p-3 bg-[var(--ocean)]/10 rounded-lg">
                <p className="font-medium text-[var(--ocean)]">Longitudinal (Fore/Aft)</p>
                <p className="text-sm text-muted-foreground">0.3-0.5g depending on ship type</p>
              </div>
              <div className="p-3 bg-[var(--logistics)]/10 rounded-lg">
                <p className="font-medium text-[var(--logistics)]">Transverse (Athwartship)</p>
                <p className="text-sm text-muted-foreground">0.5-0.8g - most critical</p>
              </div>
              <div className="p-3 bg-amber-500/10 rounded-lg">
                <p className="font-medium text-amber-600">Vertical</p>
                <p className="text-sm text-muted-foreground">0.6-1.0g - affects friction</p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Safety Factors */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-lg">
              <Weight className="h-5 w-5 text-[var(--ocean)]" />
              Safety Factors
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3">
              <li className="flex items-start gap-2">
                <CheckCircle2 className="h-4 w-4 text-[var(--logistics)] mt-0.5 shrink-0" />
                <span className="text-sm text-muted-foreground">
                  <strong>1.5:</strong> Minimum per CSS Code
                </span>
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle2 className="h-4 w-4 text-[var(--logistics)] mt-0.5 shrink-0" />
                <span className="text-sm text-muted-foreground">
                  <strong>2.0:</strong> Standard practice (recommended)
                </span>
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle2 className="h-4 w-4 text-[var(--logistics)] mt-0.5 shrink-0" />
                <span className="text-sm text-muted-foreground">
                  <strong>2.5-3.0:</strong> Heavy weather conditions
                </span>
              </li>
              <li className="flex items-start gap-2">
                <Info className="h-4 w-4 text-yellow-500 mt-0.5 shrink-0" />
                <span className="text-sm text-muted-foreground">
                  Always use SWL (Safe Working Load), not MBL
                </span>
              </li>
            </ul>
          </CardContent>
        </Card>
      </div>

      {/* Friction Reference */}
      <Card className="mt-8">
        <CardHeader>
          <CardTitle>Friction Coefficients Reference</CardTitle>
          <CardDescription>Common material combinations for cargo securing</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {[
              { materials: "Steel on Steel (dry)", mu: "0.1-0.2", note: "Lowest" },
              { materials: "Steel on Steel (oily)", mu: "0.05-0.1", note: "Avoid" },
              { materials: "Steel on Wood", mu: "0.4-0.5", note: "Good" },
              { materials: "Steel on Rubber", mu: "0.6-0.7", note: "Excellent" },
              { materials: "Wood on Steel", mu: "0.3-0.4", note: "Standard" },
              { materials: "Wood on Wood", mu: "0.3-0.5", note: "Common" },
              { materials: "Concrete on Steel", mu: "0.4-0.5", note: "Good" },
              { materials: "Rubber mat", mu: "0.6-0.8", note: "Best" },
            ].map((item) => (
              <div key={item.materials} className="p-3 bg-muted/50 rounded-lg">
                <p className="text-sm font-medium">{item.materials}</p>
                <p className="text-lg font-bold text-[var(--ocean)]">{item.mu}</p>
                <p className="text-xs text-muted-foreground">{item.note}</p>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Tips & Mistakes */}
      <div className="grid md:grid-cols-2 gap-6 mt-8">
        <Card className="border-[var(--logistics)]/20">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-lg text-[var(--logistics)]">
              <Lightbulb className="h-5 w-5" />
              Pro Tips
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3 text-sm">
              <li className="flex gap-2">
                <span className="text-[var(--logistics)]">•</span>
                Use rubber mats to maximize friction benefit
              </li>
              <li className="flex gap-2">
                <span className="text-[var(--logistics)]">•</span>
                Optimal lashing angle is 45° from horizontal
              </li>
              <li className="flex gap-2">
                <span className="text-[var(--logistics)]">•</span>
                Always protect lashings from sharp edges with edge protectors
              </li>
              <li className="flex gap-2">
                <span className="text-[var(--logistics)]">•</span>
                Re-tighten lashings 24 hours after initial tensioning
              </li>
              <li className="flex gap-2">
                <span className="text-[var(--logistics)]">•</span>
                Document the lashing plan with photos and measurements
              </li>
            </ul>
          </CardContent>
        </Card>

        <Card className="border-destructive/20">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-lg text-destructive">
              <AlertTriangle className="h-5 w-5" />
              Common Mistakes
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3 text-sm">
              <li className="flex gap-2">
                <span className="text-destructive">✗</span>
                Using MBL instead of SWL for calculations
              </li>
              <li className="flex gap-2">
                <span className="text-destructive">✗</span>
                Ignoring the effect of lashing angle
              </li>
              <li className="flex gap-2">
                <span className="text-destructive">✗</span>
                Over-tensioning causing equipment damage
              </li>
              <li className="flex gap-2">
                <span className="text-destructive">✗</span>
                Not accounting for heavy weather routes
              </li>
              <li className="flex gap-2">
                <span className="text-destructive">✗</span>
                Lashing to structurally weak points on cargo
              </li>
            </ul>
          </CardContent>
        </Card>
      </div>

      {/* FAQ Section */}
      <Card className="mt-8">
        <CardHeader>
          <CardTitle>Frequently Asked Questions</CardTitle>
        </CardHeader>
        <CardContent>
          <Accordion type="single" collapsible className="w-full">
            <AccordionItem value="q1">
              <AccordionTrigger>What is the difference between MBL and SWL?</AccordionTrigger>
              <AccordionContent>
                <strong>MBL (Minimum Breaking Load)</strong> is the force at which the equipment 
                will fail. <strong>SWL (Safe Working Load)</strong> or WLL (Working Load Limit) is 
                the maximum force the equipment should be subjected to during normal use. SWL is 
                typically 50-67% of MBL. Always use SWL for lashing calculations.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="q2">
              <AccordionTrigger>Why is transverse force most critical?</AccordionTrigger>
              <AccordionContent>
                Ships experience significant rolling in beam seas, creating large transverse 
                accelerations. Additionally, friction helps resist longitudinal forces during 
                normal operations, but has limited effect on transverse movement. Combined with 
                the typical aspect ratio of cargo (longer than wide), transverse securing 
                requires more attention.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="q3">
              <AccordionTrigger>What lashing angle should I use?</AccordionTrigger>
              <AccordionContent>
                The optimal angle is around 45° from horizontal, providing equal horizontal and 
                vertical restraint. Lower angles (30°) provide more horizontal restraint but less 
                vertical support. Higher angles (60°) provide more vertical restraint but reduced 
                horizontal holding. Choose based on cargo characteristics and available lashing points.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="q4">
              <AccordionTrigger>How often should lashings be checked during voyage?</AccordionTrigger>
              <AccordionContent>
                Lashings should be checked and re-tightened: within 24 hours of departure, 
                after passing through heavy weather, and at regular intervals (typically every 
                3-5 days for long voyages). Cargo securing arrangements can loosen due to 
                vibration, cargo settling, and material stretch.
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </CardContent>
      </Card>

      {/* Related Tools */}
      <div className="mt-12">
        <h2 className="text-xl font-bold mb-4">Related Tools</h2>
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {[
            { name: "Center of Gravity Finder", href: "/tools/project-cargo/cog-finder" },
            { name: "Ground Pressure Calculator", href: "/tools/project-cargo/ground-pressure" },
            { name: "FCL Loadability Engine", href: "/tools/ocean-freight/fcl-loadability" },
            { name: "OOG Overhang Calculator", href: "/tools/ocean-freight/oog-calculator" },
          ].map((tool) => (
            <Link key={tool.name} href={tool.href}>
              <Card className="h-full hover:shadow-md transition-all hover:border-[var(--ocean)]/50 cursor-pointer group">
                <CardContent className="p-4 flex items-center justify-between">
                  <span className="font-medium group-hover:text-[var(--ocean)] transition-colors">
                    {tool.name}
                  </span>
                  <ArrowRight className="h-4 w-4 text-muted-foreground group-hover:text-[var(--ocean)] transition-colors" />
                </CardContent>
              </Card>
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}
